// <auto-generated />
using System;
using His.Hope.PatientService.Infrastructure.Projections;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace His.Hope.PatientService.Infrastructure.Projections.Migrations
{
    [DbContext(typeof(PatientReadDbContext))]
    partial class PatientReadDbContextModelSnapshot : ModelSnapshot
    {
    protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("His.Hope.PatientService.Infrastructure.Projections.PatientProjection", b =>
                {
                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<int>("EncounterCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("encounter_count");

                    b.Property<string>("FacilityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("facility_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("gender");

                    b.Property<DateTime?>("LastVisitDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_visit_date");

                    b.Property<string>("PrimaryDiagnosis")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("primary_diagnosis");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PatientId")
                        .HasName("pk_patient_read_models");

                    b.HasIndex("FacilityId")
                        .HasDatabaseName("ix_patient_read_models_facility_id");

                    b.HasIndex("FullName")
                        .HasDatabaseName("ix_patient_read_models_full_name");

                    b.HasIndex("LastVisitDate")
                        .HasDatabaseName("ix_patient_read_models_last_visit_date");

                    b.ToTable("patient_read_models", (string)null);
        });

        modelBuilder.Entity("His.Hope.PatientService.Infrastructure.Projections.ProcessedProjectionEvent", b =>
        {
            b.Property<Guid>("EventId").HasColumnName("event_id");
            b.Property<string>("ProjectionName").HasMaxLength(200).HasColumnName("projection_name");
            b.Property<DateTimeOffset>("ProcessedAt").HasColumnName("processed_at");
            b.HasKey("EventId", "ProjectionName");
            b.ToTable("patient_processed_projection_events");
        });
#pragma warning restore 612, 618
        }
    }
}
