apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-credentials
  namespace: monitoring
type: Opaque
stringData:
  elastic-password: "CHANGE_ME_VAULT_INJECTED"
  kibana-password: "CHANGE_ME_VAULT_INJECTED"
---
apiVersion: v1
kind: Secret
metadata:
  name: es-log-credentials
  namespace: his-hope
type: Opaque
stringData:
  ES_LOG_USER: "his-hope-log-writer"
  ES_LOG_PASSWORD: "CHANGE_ME_VAULT_INJECTED"
