apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-index-template
  namespace: monitoring
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/component: logging
data:
  template.json: |
    {
      "index_patterns": ["his-hope-logs-*"],
      "template": {
        "settings": {
          "index.lifecycle.name": "his-hope-logs-policy",
          "index.lifecycle.rollover_alias": "his-hope-logs",
          "number_of_shards": 1,
          "number_of_replicas": 0
        }
      }
    }
