apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: elasticsearch-secrets
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: his-hope
    app.kubernetes.io/component: observability
spec:
  provider: vault
  parameters:
    roleName: observability
    vaultAuthMountPath: "kubernetes-jwt"
    audience: "vault"
    vaultAddress: "https://vault-active.his-hope.svc.cluster.local:8200"
    vaultSkipTLSVerify: "false"
    vaultCACertPath: "/vault/tls/ca.crt"
    objects: |
      - objectName: "elastic_password"
        secretPath: "secret/data/his-hope/observability/elasticsearch"
        secretKey: "elastic_password"
      - objectName: "kibana_password"
        secretPath: "secret/data/his-hope/observability/elasticsearch"
        secretKey: "kibana_password"
  secretObjects:
    - secretName: elasticsearch-credentials
      type: Opaque
      data:
        - objectName: elastic_password
          key: elastic-password
        - objectName: kibana_password
          key: kibana-password
