apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-spire-server-to-postgres
  namespace: spire
spec:
  podSelector:
    matchLabels:
      cnpg.io/cluster: spire-postgres
  policyTypes: [Ingress]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: spire-server
      ports:
        - protocol: TCP
          port: 5432
    - from:
        - podSelector:
            matchLabels:
              cnpg.io/cluster: spire-postgres
      ports:
        - protocol: TCP
          port: 5432
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: cnpg-system
      ports:
        - protocol: TCP
          port: 8000
