// <auto-generated />
using System;
using His.Hope.ClinicalService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace His.Hope.ClinicalService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ClinicalDbContext))]
    partial class ClinicalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("His.Hope.ClinicalService.Domain.Aggregates.Encounter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("encounter_id");

                    b.Property<Guid?>("AppointmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Assessment")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("ChiefComplaint")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DiagnosisNotes")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime>("EncounterDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncounterType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FacilityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("facility_id");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Plan")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EncounterDate")
                        .HasDatabaseName("ix_encounters_encounterdate");

                    b.HasIndex("FacilityId")
                        .HasDatabaseName("ix_encounters_facility_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_encounters_patientid");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("ix_encounters_providerid");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_encounters_status");

                    b.HasIndex("PatientId", "EncounterDate")
                        .HasDatabaseName("ix_encounters_patient_date_id");

                    b.HasIndex("ProviderId", "EncounterDate")
                        .HasDatabaseName("ix_encounters_provider_date_id");

                    b.HasIndex("FacilityId", "Status", "EncounterDate")
                        .HasDatabaseName("ix_encounters_facility_status_date_id");

                    b.ToTable("encounters", (string)null);
                });

            modelBuilder.Entity("His.Hope.ClinicalService.Domain.Entities.ClinicalNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("noteid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("createdby");

                    b.Property<Guid>("EncounterId")
                        .HasColumnType("uuid")
                        .HasColumnName("encounterid");

                    b.Property<string>("NoteType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("notetype");

                    b.HasKey("Id");

                    b.HasIndex("EncounterId");

                    b.ToTable("clinical_notes", (string)null);
                });

            modelBuilder.Entity("His.Hope.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CausationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("DeadLetteredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("LastRetryOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "OccurredOn")
                        .HasDatabaseName("ix_outboxmessages_status_occurredon");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("His.Hope.ClinicalService.Domain.Aggregates.Encounter", b =>
                {
                    b.OwnsOne("His.Hope.ClinicalService.Domain.ValueObjects.HistoryPresentIllness", "Hpi", b1 =>
                        {
                            b1.Property<Guid>("EncounterId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AggravatingFactors")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("hpi_aggravating_factors");

                            b1.Property<string>("Characteristics")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("hpi_characteristics");

                            b1.Property<string>("Duration")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("hpi_duration");

                            b1.Property<string>("Location")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("hpi_location");

                            b1.Property<string>("Onset")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("hpi_onset");

                            b1.Property<string>("PriorTreatments")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("hpi_prior_treatments");

                            b1.Property<string>("RelievingFactors")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("hpi_relieving_factors");

                            b1.HasKey("EncounterId");

                            b1.ToTable("encounters");

                            b1.WithOwner()
                                .HasForeignKey("EncounterId");
                        });

                    b.OwnsOne("His.Hope.ClinicalService.Domain.ValueObjects.VitalSigns", "VitalSigns", b1 =>
                        {
                            b1.Property<Guid>("EncounterId")
                                .HasColumnType("uuid");

                            b1.Property<decimal?>("Bmi")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("bmi");

                            b1.Property<int?>("DiastolicBP")
                                .HasColumnType("integer")
                                .HasColumnName("diastolic_bp");

                            b1.Property<int?>("HeartRate")
                                .HasColumnType("integer")
                                .HasColumnName("heart_rate");

                            b1.Property<decimal?>("HeightCm")
                                .HasPrecision(6, 2)
                                .HasColumnType("numeric(6,2)")
                                .HasColumnName("height_cm");

                            b1.Property<decimal?>("OxygenSaturation")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("oxygen_saturation");

                            b1.Property<int?>("RespiratoryRate")
                                .HasColumnType("integer")
                                .HasColumnName("respiratory_rate");

                            b1.Property<int?>("SystolicBP")
                                .HasColumnType("integer")
                                .HasColumnName("systolic_bp");

                            b1.Property<decimal?>("Temperature")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("temperature");

                            b1.Property<decimal?>("WeightKg")
                                .HasPrecision(6, 2)
                                .HasColumnType("numeric(6,2)")
                                .HasColumnName("weight_kg");

                            b1.HasKey("EncounterId");

                            b1.ToTable("encounters");

                            b1.WithOwner()
                                .HasForeignKey("EncounterId");
                        });

                    b.OwnsMany("His.Hope.ClinicalService.Domain.ValueObjects.Diagnosis", "Diagnoses", b1 =>
                        {
                            b1.Property<Guid>("encounter_id")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("ConditionName")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("condition_name");

                            b1.Property<string>("Icd10Code")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("icd10_code");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("boolean")
                                .HasColumnName("is_primary");

                            b1.Property<string>("Notes")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("notes");

                            b1.HasKey("encounter_id", "Id");

                            b1.ToTable("encounter_diagnoses", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("encounter_id");
                        });

                    b.OwnsMany("His.Hope.ClinicalService.Domain.ValueObjects.Procedure", "Procedures", b1 =>
                        {
                            b1.Property<Guid>("encounter_id")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("CptCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("cpt_code");

                            b1.Property<string>("Notes")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("notes");

                            b1.Property<DateTime>("PerformedDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("performed_date");

                            b1.Property<string>("ProcedureName")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("procedure_name");

                            b1.HasKey("encounter_id", "Id");

                            b1.ToTable("encounter_procedures", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("encounter_id");
                        });

                    b.Navigation("Diagnoses");

                    b.Navigation("Hpi");

                    b.Navigation("Procedures");

                    b.Navigation("VitalSigns");
                });
#pragma warning restore 612, 618
        }
    }
}
