sonar.projectKey=his-hope
sonar.projectName=His.Hope Hospital Information System
sonar.organization=his-hope
sonar.sources=src/
sonar.tests=tests/
sonar.test.inclusions=tests/**/*Test*.cs,tests/**/*Tests.cs,src/Frontend/his-hope-app/src/**/*.spec.ts
sonar.exclusions=**/bin/**,**/obj/**,**/node_modules/**,**/Migrations/**
sonar.cs.opencover.reportsPaths=coverage-results/**/coverage.opencover.xml
sonar.cs.coverageplugin=Coverlet
sonar.javascript.lcov.reportPaths=src/Frontend/his-hope-app/coverage/lcov.info
sonar.coverage.exclusions=**/*.model.ts,**/mock/**
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
