apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-bff
spec:
  template:
    spec:
      containers:
        - name: billing-bff
          env:
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:5400
          envFrom:
            - configMapRef:
                name: his-hope-runtime-contract-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinical-bff
spec:
  template:
    spec:
      containers:
        - name: clinical-bff
          env:
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:5200
          envFrom:
            - configMapRef:
                name: his-hope-runtime-contract-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-bff
spec:
  template:
    spec:
      containers:
        - name: dashboard-bff
          env:
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:5600
          envFrom:
            - configMapRef:
                name: his-hope-runtime-contract-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-bff
spec:
  template:
    spec:
      containers:
        - name: patient-bff
          env:
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:5100
          envFrom:
            - configMapRef:
                name: his-hope-runtime-contract-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-bff
spec:
  template:
    spec:
      containers:
        - name: lab-bff
          env:
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:5300
          envFrom:
            - configMapRef:
                name: his-hope-runtime-contract-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pharmacy-bff
spec:
  template:
    spec:
      containers:
        - name: pharmacy-bff
          env:
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:5500
          envFrom:
            - configMapRef:
                name: his-hope-runtime-contract-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: systemdashboard-bff
spec:
  template:
    spec:
      containers:
        - name: systemdashboard-bff
          envFrom:
            - configMapRef:
                name: his-hope-runtime-contract-config
