apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache-alias
spec:
  type: ExternalName
  externalName: his-hope-redis.his-hope-data.svc.cluster.local
  ports:
    - name: redis
      port: 6379
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: messaging-alias
spec:
  type: ExternalName
  externalName: his-hope-rabbitmq.his-hope-data.svc.cluster.local
  ports:
    - name: amqp
      port: 5672
      protocol: TCP
