apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-continuity
spec:
  template:
    spec:
      containers:
        - name: database-continuity
          env:
            - name: PGHOST
              value: his-hope-postgres.his-hope-data.svc.cluster.local
