- op: add
  path: /spec/template/metadata/annotations/linkerd.io~1inject
  value: disabled
- op: remove
  path: /spec/template/spec/hostPID
- op: replace
  path: /spec/template/spec/containers/0/env/23/value
  value: kubernetes
- op: replace
  path: /spec/template/spec/containers/0/env/24/value
  value: kubernetes
- op: remove
  path: /spec/template/spec/containers/0/env/27
- op: remove
  path: /spec/template/spec/containers/0/env/26
- op: remove
  path: /spec/template/spec/containers/1
- op: remove
  path: /spec/template/spec/volumes/1
- op: remove
  path: /spec/template/spec/volumes/0
