apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: his-hope-

commonLabels:
  app.kubernetes.io/part-of: his-hope
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/version: latest

commonAnnotations:
  linkerd.io/inject: enabled

resources:
  - ../../base
  - ../../linkerd/server.yaml
  - ../../linkerd/server-authorization.yaml
  - ../../linkerd/traffic-split.yaml
  - ../../linkerd/service-profiles.yaml
  - ../../linkerd/pod-monitor.yaml
  - ../../infrastructure/pgbouncer-configmap.yaml
  - ../../infrastructure/pgbouncer-secret.yaml
  - ../../infrastructure/unleash-deployment.yaml
  - ../../priority/priority-classes.yaml
  - ../../security/gatekeeper-constraints.yaml
  - ../../vault/vault-statefulset.yaml
  - ../../vault/vault-agent-injector.yaml
  - ../../vault/vault-csi-provider.yaml

patches:
  - path: identity-security-patch.yaml
  - target:
      kind: Deployment
      labelSelector: "app.kubernetes.io/component=backend"
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: Jwt__RsaEncryptionPrivateKeyPath
          value: /mnt/oidc-secrets/private_key
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: oidc-encryption-key
          secret:
            secretName: identity-service-oidc-encryption
            defaultMode: 0440
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: oidc-encryption-key
          mountPath: /mnt/oidc-secrets
          readOnly: true
  - target:
      kind: Deployment
      labelSelector: "app.kubernetes.io/part-of=his-hope"
    patch: |
      - op: add
        path: /spec/template/metadata/annotations
        value:
          vault.hashicorp.com/agent-inject: "true"
          vault.hashicorp.com/role: "default"
          vault.hashicorp.com/agent-inject-status: "update"
          vault.hashicorp.com/agent-pre-populate: "true"
          vault.hashicorp.com/agent-pre-populate-only: "false"
          linkerd.io/inject: enabled

components:
  - image-digests

namespace: his-hope

replicas:
  - name: patient-service
    count: 5
  - name: identity-service
    count: 3
  - name: clinical-service
    count: 5
  - name: appointment-service
    count: 3
  - name: vault-agent-injector
    count: 2

configMapGenerator:
  - name: vault-agent-config
    namespace: his-hope
    literals:
      - vault.skip-verify=false
      - vault.address=https://vault-active.his-hope.svc.cluster.local:8200
