apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
$patch: delete
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
$patch: delete
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
$patch: delete
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
$patch: delete
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
$patch: delete
---
apiVersion: v1
kind: Service
metadata:
  name: redis
$patch: delete
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
$patch: delete
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
$patch: delete
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
$patch: delete
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgres
$patch: delete
