apiVersion: v1
kind: ConfigMap
metadata:
  name: runtime-contract-config
data:
  SERVICE_PROMETHEUS_URL: http://kps-kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
  SERVICE_ALERTMANAGER_URL: http://kps-kube-prometheus-stack-alertmanager.monitoring.svc.cluster.local:9093
  OBSERVABILITY_PROMETHEUS_URL: http://kps-kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
  OBSERVABILITY_ALERTMANAGER_URL: http://kps-kube-prometheus-stack-alertmanager.monitoring.svc.cluster.local:9093
  OBSERVABILITY_LOKI_URL: http://loki.monitoring.svc.cluster.local:3100
  OBSERVABILITY_JAEGER_URL: http://jaeger.monitoring.svc.cluster.local:16686
  ADAPTER_RABBITMQ_HOST: his-hope-rabbitmq.his-hope-data.svc.cluster.local
  RABBITMQ_URL: amqp://his_hope_app@his-hope-rabbitmq.his-hope-data.svc.cluster.local:5672
  ADAPTER_GRPC_APPOINTMENT_URL: http://his-hope-appointment-service.his-hope.svc.cluster.local:5008
  ADAPTER_GRPC_BILLING_URL: http://his-hope-billing-service.his-hope.svc.cluster.local:5022
  ADAPTER_GRPC_CLINICAL_URL: http://his-hope-clinical-service.his-hope.svc.cluster.local:5009
  ADAPTER_GRPC_LAB_URL: http://his-hope-lab-service.his-hope.svc.cluster.local:5012
  ADAPTER_GRPC_PATIENT_URL: http://his-hope-patient-service.his-hope.svc.cluster.local:5006
  ADAPTER_GRPC_PHARMACY_URL: http://his-hope-pharmacy-service.his-hope.svc.cluster.local:5032
  ADAPTER_SERVICE_APPOINTMENT_HTTP: http://his-hope-appointment-service.his-hope.svc.cluster.local:5004
  ADAPTER_SERVICE_BILLING_HTTP: http://his-hope-billing-service.his-hope.svc.cluster.local:5020
  ADAPTER_SERVICE_CLINICAL_HTTP: http://his-hope-clinical-service.his-hope.svc.cluster.local:5005
  ADAPTER_SERVICE_DASHBOARD_BFF_HTTP: http://his-hope-dashboard-bff.his-hope.svc.cluster.local:5600
  ADAPTER_SERVICE_IDENTITY_HTTP: http://his-hope-identity-service.his-hope.svc.cluster.local:5003
  ADAPTER_SERVICE_LAB_HTTP: http://his-hope-lab-service.his-hope.svc.cluster.local:5010
  ADAPTER_SERVICE_PATIENT_HTTP: http://his-hope-patient-service.his-hope.svc.cluster.local:5002
  ADAPTER_SERVICE_PHARMACY_HTTP: http://his-hope-pharmacy-service.his-hope.svc.cluster.local:5030
  SERVICE_API_GATEWAY_URL: http://his-hope-api-gateway.his-hope.svc.cluster.local:5000
  SERVICE_APPOINTMENT_API_URL: http://his-hope-appointment-service.his-hope.svc.cluster.local:5004
  SERVICE_APPOINTMENT_GRPC_URL: http://his-hope-appointment-service.his-hope.svc.cluster.local:5008
  SERVICE_APPOINTMENT_URL: http://his-hope-appointment-service.his-hope.svc.cluster.local:5004
  SERVICE_BILLING_API_URL: http://his-hope-billing-service.his-hope.svc.cluster.local:5020
  SERVICE_BILLING_BFF_URL: http://his-hope-billing-bff.his-hope.svc.cluster.local:5400
  SERVICE_BILLING_GRPC_URL: http://his-hope-billing-service.his-hope.svc.cluster.local:5022
  SERVICE_BILLING_URL: http://his-hope-billing-service.his-hope.svc.cluster.local:5020
  SERVICE_CLINICAL_API_URL: http://his-hope-clinical-service.his-hope.svc.cluster.local:5005
  SERVICE_CLINICAL_BFF_URL: http://his-hope-clinical-bff.his-hope.svc.cluster.local:5200
  SERVICE_CLINICAL_GRPC_URL: http://his-hope-clinical-service.his-hope.svc.cluster.local:5009
  SERVICE_CLINICAL_URL: http://his-hope-clinical-service.his-hope.svc.cluster.local:5005
  SERVICE_DASHBOARD_BFF_API_URL: http://his-hope-dashboard-bff.his-hope.svc.cluster.local:5600
  SERVICE_DASHBOARD_BFF_URL: http://his-hope-dashboard-bff.his-hope.svc.cluster.local:5600
  SERVICE_DATABASE_CONTINUITY_API_URL: http://his-hope-database-continuity.his-hope.svc.cluster.local:5800
  SERVICE_DATABASE_CONTINUITY_URL: http://his-hope-database-continuity.his-hope.svc.cluster.local:5800
  SERVICE_IDENTITY_API_URL: http://his-hope-identity-service.his-hope.svc.cluster.local:5003
  SERVICE_IDENTITY_GRPC_URL: http://his-hope-identity-service.his-hope.svc.cluster.local:5007
  SERVICE_IDENTITY_URL: http://his-hope-identity-service.his-hope.svc.cluster.local:5003
  SERVICE_LAB_API_URL: http://his-hope-lab-service.his-hope.svc.cluster.local:5010
  SERVICE_LAB_BFF_URL: http://his-hope-lab-bff.his-hope.svc.cluster.local:5300
  SERVICE_LAB_GRPC_URL: http://his-hope-lab-service.his-hope.svc.cluster.local:5012
  SERVICE_LAB_URL: http://his-hope-lab-service.his-hope.svc.cluster.local:5010
  SERVICE_PATIENT_API_URL: http://his-hope-patient-service.his-hope.svc.cluster.local:5002
  SERVICE_PATIENT_BFF_URL: http://his-hope-patient-bff.his-hope.svc.cluster.local:5100
  SERVICE_PATIENT_GRPC_URL: http://his-hope-patient-service.his-hope.svc.cluster.local:5006
  SERVICE_PATIENT_URL: http://his-hope-patient-service.his-hope.svc.cluster.local:5002
  SERVICE_PHARMACY_API_URL: http://his-hope-pharmacy-service.his-hope.svc.cluster.local:5030
  SERVICE_PHARMACY_BFF_URL: http://his-hope-pharmacy-bff.his-hope.svc.cluster.local:5500
  SERVICE_PHARMACY_GRPC_URL: http://his-hope-pharmacy-service.his-hope.svc.cluster.local:5032
  SERVICE_PHARMACY_URL: http://his-hope-pharmacy-service.his-hope.svc.cluster.local:5030
