apiVersion: v1
kind: ConfigMap
metadata:
  name: runtime-contract-config
data:
  DATABASE_POSTGRES_URL: postgresql://his_hope_app@his-hope-postgres.his-hope-data.svc.cluster.local:5432/hishope
  REDIS_URL: redis://his-hope-redis.his-hope-data.svc.cluster.local:6379
  ADAPTER_REDIS_CONNECTION_STRING: his-hope-redis.his-hope-data.svc.cluster.local:6379
  ADAPTER_CONNECTIONSTRINGS_APPOINTMENTDB: Server=his-hope-postgres.his-hope-data.svc.cluster.local;Port=5432;Database=appointmentdb;Username=his_hope;Password=
  ADAPTER_CONNECTIONSTRINGS_BILLINGDB: Server=his-hope-postgres.his-hope-data.svc.cluster.local;Port=5432;Database=billingdb;Username=his_hope;Password=
  ADAPTER_CONNECTIONSTRINGS_CLINICALDB: Server=his-hope-postgres.his-hope-data.svc.cluster.local;Port=5432;Database=clinicaldb;Username=his_hope;Password=
  ADAPTER_CONNECTIONSTRINGS_IDENTITYDB: Server=his-hope-postgres.his-hope-data.svc.cluster.local;Port=5432;Database=identitydb;Username=his_hope;Password=
  ADAPTER_CONNECTIONSTRINGS_LABDB: Server=his-hope-postgres.his-hope-data.svc.cluster.local;Port=5432;Database=labdb;Username=his_hope;Password=
  ADAPTER_CONNECTIONSTRINGS_PATIENTDB: Server=his-hope-postgres.his-hope-data.svc.cluster.local;Port=5432;Database=patientdb;Username=his_hope;Password=
  ADAPTER_CONNECTIONSTRINGS_PHARMACYDB: Server=his-hope-postgres.his-hope-data.svc.cluster.local;Port=5432;Database=pharmacydb;Username=his_hope;Password=
