apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
spec:
  template:
    spec:
      containers:
        - name: spire-jwt-fetcher
          securityContext:
            readOnlyRootFilesystem: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service
spec:
  template:
    spec:
      containers:
        - name: spire-jwt-fetcher
          securityContext:
            readOnlyRootFilesystem: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinical-service
spec:
  template:
    spec:
      containers:
        - name: spire-jwt-fetcher
          securityContext:
            readOnlyRootFilesystem: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-service
spec:
  template:
    spec:
      containers:
        - name: spire-jwt-fetcher
          securityContext:
            readOnlyRootFilesystem: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
spec:
  template:
    spec:
      containers:
        - name: spire-jwt-fetcher
          securityContext:
            readOnlyRootFilesystem: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pharmacy-service
spec:
  template:
    spec:
      containers:
        - name: spire-jwt-fetcher
          securityContext:
            readOnlyRootFilesystem: true
