import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HisHopeDataTableCellDirective, HisHopeDataTableColumn, HisHopeDataTableComponent, HisHopeI18nService, HisHopePageHeaderComponent, HisHopePageLayoutComponent, HisHopePermissionService, HisHopeToolbarComponent, HisHopeTranslatePipe } from '@his-hope/frontend-foundation';
import { AdminApiService } from '../../core/services/admin-api.service';

@Component({selector:'app-iam-workload-sessions-page',standalone:true,imports:[CommonModule,HisHopeDataTableCellDirective,HisHopeDataTableComponent,HisHopePageHeaderComponent,HisHopePageLayoutComponent,HisHopeToolbarComponent,HisHopeTranslatePipe],template:`<hh-page-layout><hh-page-header hhPageHeader [title]="'admin.workloadSessions'|hhTranslate:'Workload sessions'"/><hh-toolbar hhPageToolbar><button hhToolbarActions type="button" class="hh-button hh-button--secondary" (click)="load()">{{'admin.refresh'|hhTranslate}}</button></hh-toolbar><div *ngIf="error" class="hh-state hh-state--error">{{error}}</div><hh-data-table [columns]="columns" [rows]="rows" [loading]="loading" [empty]="!loading&&!rows.length"><ng-template hhDataTableCell="actions" let-row><button *ngIf="canWrite" type="button" class="hh-button hh-button--danger hh-button--small" (click)="revoke(row)">{{'admin.revoke'|hhTranslate}}</button></ng-template></hh-data-table></hh-page-layout>`})
export class IamWorkloadSessionsPageComponent implements OnInit {private readonly api=inject(AdminApiService);private readonly permissions=inject(HisHopePermissionService);private readonly i18n=inject(HisHopeI18nService);get canWrite(){return this.permissions.has('admin.sessions.write');}rows:Record<string,unknown>[]=[];loading=false;error='';get columns():HisHopeDataTableColumn[]{return[{key:'sessionId',label:this.i18n.t('admin.sessionId','Session ID')},{key:'workloadRoleId',label:this.i18n.t('admin.workloadRole','Workload role')},{key:'clientId',label:this.i18n.t('admin.clientId','Client ID')},{key:'expiresAt',label:this.i18n.t('admin.expiresAt','Expires')},{key:'actions',label:this.i18n.t('admin.actions','Actions'),sortable:false}];}ngOnInit(){this.load();}load(){this.loading=true;this.api.getIamWorkloadSessionCatalog().subscribe({next:x=>this.rows=x.sessions.map(item=>({...item})),error:()=>{this.error=this.i18n.t('admin.iamLoadFailed','Unable to load workload sessions.');this.loading=false;},complete:()=>this.loading=false});}revoke(row:Record<string,unknown>){const roleId=String(row['workloadRoleId']??''),id=String(row['sessionId']??'');if(!this.canWrite||!roleId||!id)return;this.api.revokeIamWorkloadSession(roleId,id).subscribe({next:()=>this.load(),error:()=>this.error=this.i18n.t('admin.iamSaveFailed','Unable to revoke workload session.')});}}

@Component({selector:'app-iam-audit-integrations-page',standalone:true,imports:[CommonModule,HisHopeDataTableCellDirective,HisHopeDataTableComponent,HisHopePageHeaderComponent,HisHopePageLayoutComponent,HisHopeToolbarComponent,HisHopeTranslatePipe],template:`<hh-page-layout><hh-page-header hhPageHeader [title]="'admin.auditIntegrations'|hhTranslate:'Audit & integrations'"/><hh-toolbar hhPageToolbar><button hhToolbarActions type="button" class="hh-button hh-button--secondary" (click)="load()">{{'admin.refresh'|hhTranslate}}</button></hh-toolbar><section *ngIf="integration" class="hh-form-card"><p>Audit append-only: <strong>{{integration.audit.appendOnly}}</strong></p><p>SSF: <strong>{{integration.ssf.enabled}}</strong> · {{integration.ssf.pending}} pending</p></section><div *ngIf="error" class="hh-state hh-state--error">{{error}}</div><hh-data-table [columns]="columns" [rows]="rows" [loading]="loading" [empty]="!loading&&!rows.length"><ng-template hhDataTableCell="actions" let-row><button *ngIf="canWrite" type="button" class="hh-button hh-button--secondary hh-button--small" (click)="retry(row)">{{'admin.retry'|hhTranslate}}</button></ng-template></hh-data-table></hh-page-layout>`})
export class IamAuditIntegrationsPageComponent implements OnInit {private readonly api=inject(AdminApiService);private readonly permissions=inject(HisHopePermissionService);private readonly i18n=inject(HisHopeI18nService);get canWrite(){return this.permissions.has('admin.audit.write');}integration:any;rows:Record<string,unknown>[]=[];loading=false;error='';get columns():HisHopeDataTableColumn[]{return[{key:'eventType',label:this.i18n.t('admin.eventType','Event')},{key:'createdAt',label:this.i18n.t('admin.createdAt','Created')},{key:'attempts',label:this.i18n.t('admin.attempts','Attempts')},{key:'lastError',label:this.i18n.t('admin.error','Error')},{key:'actions',label:this.i18n.t('admin.actions','Actions'),sortable:false}];}ngOnInit(){this.load();}load(){this.loading=true;this.api.getIamAuditIntegrations().subscribe({next:x=>this.integration=x,error:()=>this.error=this.i18n.t('admin.iamLoadFailed','Unable to load integration posture.')});this.api.getSecuritySignalOutbox().subscribe({next:x=>{this.rows=x.map(item=>({...item}));this.loading=false;},error:()=>{this.error=this.i18n.t('admin.iamLoadFailed','Unable to load security signals.');this.loading=false;}});}retry(row:Record<string,unknown>){const id=String(row['id']??'');if(!this.canWrite||!id)return;this.api.retrySecuritySignal(id).subscribe({next:()=>this.load(),error:()=>this.error=this.i18n.t('admin.iamSaveFailed','Unable to retry security signal.')});}}
