// <auto-generated />
using System;
using His.Hope.LabService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace His.Hope.LabService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LabDbContext))]
    [Migration("20260827084631___SnapshotSync")]
    partial class __SnapshotSync
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("His.Hope.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CausationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("causation_id");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("claimed_by");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeadLetteredOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dead_lettered_on");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastRetryOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_retry_on");

                    b.Property<DateTime?>("LockExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lock_expires_at");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Status", "OccurredOn");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("His.Hope.LabService.Domain.Aggregates.LabOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("deleted_by");

                    b.Property<Guid?>("EncounterId")
                        .HasColumnType("uuid")
                        .HasColumnName("encounterid");

                    b.Property<string>("FacilityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("facilityid");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("orderdate");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patientid");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("providerid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.HasIndex("OrderDate");

                    b.HasIndex("PatientId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("Status");

                    b.HasIndex("PatientId", "OrderDate")
                        .HasDatabaseName("IX_LabOrders_Patient_Date_Id");

                    b.HasIndex("FacilityId", "Status", "OrderDate")
                        .HasDatabaseName("IX_LabOrders_Facility_Status_Date_Id");

                    b.ToTable("lab_orders", null, t =>
                        {
                            t.Property("CreatedAt")
                                .HasColumnName("created_at");

                            t.Property("EncounterId")
                                .HasColumnName("encounter_id");

                            t.Property("FacilityId")
                                .HasColumnName("facility_id");

                            t.Property("OrderDate")
                                .HasColumnName("order_date");

                            t.Property("PatientId")
                                .HasColumnName("patient_id");

                            t.Property("ProviderId")
                                .HasColumnName("provider_id");

                            t.Property("UpdatedAt")
                                .HasColumnName("updated_at");
                        });

                    b.HasAnnotation("HisHope:SoftDelete", true);
                });

            modelBuilder.Entity("His.Hope.LabService.Domain.Entities.CriticalAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledgedat");

                    b.Property<string>("AcknowledgedByDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("acknowledgedbydisplayname");

                    b.Property<string>("AcknowledgedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("acknowledgedbyuserid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("deleted_by");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("LabOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("laborderid");

                    b.Property<Guid>("LabResultId")
                        .HasColumnType("uuid")
                        .HasColumnName("labresultid");

                    b.Property<Guid>("LabTestId")
                        .HasColumnType("uuid")
                        .HasColumnName("labtestid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolvedat");

                    b.Property<string>("ResolvedByDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("resolvedbydisplayname");

                    b.Property<string>("ResolvedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("resolvedbyuserid");

                    b.Property<string>("ResultUnit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("resultunit");

                    b.Property<string>("ResultValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("resultvalue");

                    b.Property<Guid?>("RuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("ruleid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<decimal?>("ThresholdValue")
                        .HasColumnType("numeric")
                        .HasColumnName("thresholdvalue");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("triggertype");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("LabOrderId", "LabTestId")
                        .IsUnique()
                        .HasFilter("status <> 'RESOLVED'");

                    b.ToTable("critical_alerts", null, t =>
                        {
                            t.Property("AcknowledgedAt")
                                .HasColumnName("acknowledged_at");

                            t.Property("AcknowledgedByDisplayName")
                                .HasColumnName("acknowledged_by_display_name");

                            t.Property("AcknowledgedByUserId")
                                .HasColumnName("acknowledged_by_user_id");

                            t.Property("CreatedAt")
                                .HasColumnName("created_at");

                            t.Property("LabOrderId")
                                .HasColumnName("lab_order_id");

                            t.Property("LabResultId")
                                .HasColumnName("lab_result_id");

                            t.Property("LabTestId")
                                .HasColumnName("lab_test_id");

                            t.Property("ResolvedAt")
                                .HasColumnName("resolved_at");

                            t.Property("ResolvedByDisplayName")
                                .HasColumnName("resolved_by_display_name");

                            t.Property("ResolvedByUserId")
                                .HasColumnName("resolved_by_user_id");

                            t.Property("ResultUnit")
                                .HasColumnName("result_unit");

                            t.Property("ResultValue")
                                .HasColumnName("result_value");

                            t.Property("RuleId")
                                .HasColumnName("rule_id");

                            t.Property("ThresholdValue")
                                .HasColumnName("threshold_value");

                            t.Property("TriggerType")
                                .HasColumnName("trigger_type");

                            t.Property("UpdatedAt")
                                .HasColumnName("updated_at");
                        });
                });

            modelBuilder.Entity("His.Hope.LabService.Domain.Entities.CriticalAlertAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<string>("ActorDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actordisplayname");

                    b.Property<string>("ActorUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("actoruserid");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CriticalAlertId")
                        .HasColumnType("uuid")
                        .HasColumnName("criticalalertid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("deleted_by");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurredat");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("CriticalAlertId");

                    b.HasIndex("OccurredAt");

                    b.ToTable("critical_alert_audit_entries", null, t =>
                        {
                            t.Property("ActorDisplayName")
                                .HasColumnName("actor_display_name");

                            t.Property("ActorUserId")
                                .HasColumnName("actor_user_id");

                            t.Property("CriticalAlertId")
                                .HasColumnName("critical_alert_id");

                            t.Property("OccurredAt")
                                .HasColumnName("occurred_at");
                        });
                });

            modelBuilder.Entity("His.Hope.LabService.Domain.Entities.CriticalAlertRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedByDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("createdbydisplayname");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("createdbyuserid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("deleted_by");

                    b.Property<decimal?>("HighCriticalValue")
                        .HasColumnType("numeric")
                        .HasColumnName("highcriticalvalue");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<decimal?>("LowCriticalValue")
                        .HasColumnType("numeric")
                        .HasColumnName("lowcriticalvalue");

                    b.Property<string>("TestCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("testcode");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("testname");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("TestCode");

                    b.HasIndex("TestCode", "IsActive");

                    b.ToTable("critical_alert_rules", null, t =>
                        {
                            t.Property("CreatedAt")
                                .HasColumnName("created_at");

                            t.Property("CreatedByDisplayName")
                                .HasColumnName("created_by_display_name");

                            t.Property("CreatedByUserId")
                                .HasColumnName("created_by_user_id");

                            t.Property("HighCriticalValue")
                                .HasColumnName("high_critical_value");

                            t.Property("IsActive")
                                .HasColumnName("is_active");

                            t.Property("LowCriticalValue")
                                .HasColumnName("low_critical_value");

                            t.Property("TestCode")
                                .HasColumnName("test_code");

                            t.Property("TestName")
                                .HasColumnName("test_name");

                            t.Property("UpdatedAt")
                                .HasColumnName("updated_at");
                        });
                });

            modelBuilder.Entity("His.Hope.LabService.Domain.Aggregates.LabOrder", b =>
                {
                    b.OwnsMany("His.Hope.LabService.Domain.Entities.LabTest", "RequestedTests", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime?>("CollectedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("collectedat");

                            b1.Property<DateTime?>("CompletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("completedat");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at")
                                .HasDefaultValueSql("CURRENT_TIMESTAMP");

                            b1.Property<string>("CreatedBy")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("created_by");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("deleted_at");

                            b1.Property<string>("DeletedBy")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("deleted_by");

                            b1.Property<bool?>("IsDeleted")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("is_deleted");

                            b1.Property<Guid>("LabOrderId")
                                .HasColumnType("uuid")
                                .HasColumnName("laborderid");

                            b1.Property<DateTime>("OrderedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("orderedat");

                            b1.Property<string>("SpecimenType")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("specimentype");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("status");

                            b1.Property<string>("TestCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("testcode");

                            b1.Property<string>("TestName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("testname");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.Property<string>("UpdatedBy")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("updated_by");

                            b1.HasKey("Id");

                            b1.HasIndex("LabOrderId");

                            b1.ToTable("lab_tests", null, t =>
                                {
                                    t.Property("CollectedAt")
                                        .HasColumnName("collected_at");

                                    t.Property("CompletedAt")
                                        .HasColumnName("completed_at");

                                    t.Property("CreatedAt")
                                        .HasColumnName("created_at");

                                    t.Property("LabOrderId")
                                        .HasColumnName("lab_order_id");

                                    t.Property("OrderedAt")
                                        .HasColumnName("ordered_at");

                                    t.Property("SpecimenType")
                                        .HasColumnName("specimen_type");

                                    t.Property("TestCode")
                                        .HasColumnName("test_code");

                                    t.Property("TestName")
                                        .HasColumnName("test_name");

                                    t.Property("UpdatedAt")
                                        .HasColumnName("updated_at");
                                });

                            b1.WithOwner()
                                .HasForeignKey("LabOrderId");

                            b1.OwnsOne("His.Hope.LabService.Domain.Entities.LabResult", "Result", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("AbnormalFlag")
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("abnormalflag");

                                    b2.Property<DateTime?>("CreatedAt")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("created_at")
                                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                                    b2.Property<string>("CreatedBy")
                                        .HasMaxLength(256)
                                        .HasColumnType("character varying(256)")
                                        .HasColumnName("created_by");

                                    b2.Property<DateTime?>("DeletedAt")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("deleted_at");

                                    b2.Property<string>("DeletedBy")
                                        .HasMaxLength(256)
                                        .HasColumnType("character varying(256)")
                                        .HasColumnName("deleted_by");

                                    b2.Property<bool?>("IsDeleted")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("boolean")
                                        .HasDefaultValue(false)
                                        .HasColumnName("is_deleted");

                                    b2.Property<Guid>("LabResultId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("labresultid");

                                    b2.Property<Guid>("LabTestId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("labtestid");

                                    b2.Property<string>("Notes")
                                        .HasMaxLength(1000)
                                        .HasColumnType("character varying(1000)")
                                        .HasColumnName("notes");

                                    b2.Property<string>("PerformedBy")
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("performedby");

                                    b2.Property<string>("ReferenceRange")
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("referencerange");

                                    b2.Property<string>("ResultStatus")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("resultstatus");

                                    b2.Property<DateTime>("ResultedAt")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("resultedat");

                                    b2.Property<string>("Unit")
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("unit");

                                    b2.Property<DateTime?>("UpdatedAt")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("updated_at");

                                    b2.Property<string>("UpdatedBy")
                                        .HasMaxLength(256)
                                        .HasColumnType("character varying(256)")
                                        .HasColumnName("updated_by");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("character varying(500)")
                                        .HasColumnName("value");

                                    b2.HasKey("Id");

                                    b2.HasIndex("LabTestId")
                                        .IsUnique();

                                    b2.ToTable("lab_results", null, t =>
                                        {
                                            t.Property("AbnormalFlag")
                                                .HasColumnName("abnormal_flag");

                                            t.Property("LabResultId")
                                                .HasColumnName("lab_result_id");

                                            t.Property("LabTestId")
                                                .HasColumnName("lab_test_id");

                                            t.Property("PerformedBy")
                                                .HasColumnName("performed_by");

                                            t.Property("ReferenceRange")
                                                .HasColumnName("reference_range");

                                            t.Property("ResultStatus")
                                                .HasColumnName("result_status");

                                            t.Property("ResultedAt")
                                                .HasColumnName("resulted_at");
                                        });

                                    b2.WithOwner()
                                        .HasForeignKey("LabTestId");
                                });

                            b1.Navigation("Result");
                        });

                    b.Navigation("RequestedTests");
                });

            modelBuilder.Entity("His.Hope.LabService.Domain.Entities.CriticalAlertAuditEntry", b =>
                {
                    b.HasOne("His.Hope.LabService.Domain.Entities.CriticalAlert", null)
                        .WithMany("AuditEntries")
                        .HasForeignKey("CriticalAlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("His.Hope.LabService.Domain.Entities.CriticalAlert", b =>
                {
                    b.Navigation("AuditEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
