// ─── OpenIddict Custom Event Handlers ─────────────────────────────────────
//<auto-generated/>
namespace His.Hope.IdentityService.Api.Handlers;

using global::OpenIddict.Server;
using global::OpenIddict.Server.AspNetCore;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Http;

/// <summary>
/// Custom OpenIddict server event handler that fixes the <see cref="BaseContext.BaseUri"/>
/// used for discovery document endpoint URLs by reading the <c>X-Forwarded-Host</c>
/// header directly from the ASP.NET Core request.
///
/// This bypasses the <c>ForwardedHeadersMiddleware</c>, which may skip processing
/// when the Docker network source IP does not match the configured
/// <c>KnownNetworks</c> entries (or when YARP re-encodes the Host header).
///
/// <para>
/// <b>Order:</b> Runs before <c>AttachIssuer</c> and <c>AttachEndpoints</c>,
/// which construct the discovery document endpoint URLs from
/// <see cref="HandleConfigurationRequestContext.BaseUri"/>.
/// </para>
/// </summary>
public sealed class FixDiscoveryBaseUriHandler
    : IOpenIddictServerHandler<OpenIddictServerEvents.HandleConfigurationRequestContext>
{
    /// <summary>
    /// Gets the default descriptor definition assigned to this handler.
    /// </summary>
    public static OpenIddictServerHandlerDescriptor Descriptor { get; }
        = OpenIddictServerHandlerDescriptor.CreateBuilder<OpenIddictServerEvents.HandleConfigurationRequestContext>()
            .UseSingletonHandler<FixDiscoveryBaseUriHandler>()
            .SetOrder(int.MaxValue - 200_000) // Before AttachIssuer (int.MaxValue - 100_000)
            .SetType(OpenIddictServerHandlerType.Custom)
            .Build();

    /// <inheritdoc/>
    public ValueTask HandleAsync(OpenIddictServerEvents.HandleConfigurationRequestContext context)
    {
        if (context is null)
        {
            throw new ArgumentNullException(nameof(context));
        }

        // Get the ASP.NET Core HttpRequest from the transaction properties.
        var request = context.Transaction.GetHttpRequest();
        if (request is null)
        {
            return default;
        }

        // Read X-Forwarded-Host directly from the request headers.
        // Nginx sets this via `proxy_set_header X-Forwarded-Host $http_host`
        // in the /connect/ and /.well-known/ location blocks, so the value
        // should be something like "localhost:8081".
        //
        // If the ForwardedHeadersMiddleware already processed this header,
        // request.Host will already be correct — but we read the raw header
        // to handle cases where the middleware skipped processing (e.g. due
        // to Docker network source IP not matching KnownNetworks).
        if (!request.Headers.TryGetValue("X-Forwarded-Host", out var forwardedHosts) ||
            forwardedHosts.Count <= 0 ||
            string.IsNullOrEmpty(forwardedHosts[0]))
        {
            // No X-Forwarded-Host header — nothing to fix.
            return default;
        }

        var forwardedHost = forwardedHosts[0];

        // Determine the correct scheme from X-Forwarded-Proto if available.
        var scheme = request.Scheme;
        if (request.Headers.TryGetValue("X-Forwarded-Proto", out var forwardedProtos) &&
            forwardedProtos.Count > 0 &&
            !string.IsNullOrEmpty(forwardedProtos[0]))
        {
            scheme = forwardedProtos[0];
        }

        // Construct the correct public base URI from the forwarded headers.
        // This produces e.g. "http://localhost:8081" instead of "http://localhost".
        context.BaseUri = new Uri($"{scheme}://{forwardedHost}{request.PathBase}", UriKind.Absolute);

        return default;
    }
}
