apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-agent
  namespace: spire
data:
  agent.conf: |
    agent {
      data_dir = "/run/spire/data"
      log_level = "INFO"
      server_address = "spire-server.spire.svc.cluster.local"
      server_port = "8081"
      socket_path = "/run/spire/sockets/agent.sock"
      trust_bundle_path = "/run/spire/bundle/bundle.crt"
      trust_domain = "his-hope.local"
    }

    plugins {
      NodeAttestor "k8s_psat" {
        plugin_data {
          cluster = "his-hope-k3s"
        }
      }

      KeyManager "disk" {
        plugin_data {
          directory = "/run/spire/data"
        }
      }

      WorkloadAttestor "k8s" {
        plugin_data {
          node_name_env = "MY_NODE_NAME"
          kubelet_secure_port = 10250
          kubelet_ca_path = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
          token_path = "/var/run/secrets/kubernetes.io/serviceaccount/token"
          disable_container_selectors = true
        }
      }

      WorkloadAttestor "unix" {
        plugin_data {}
      }
    }

    health_checks {
      listener_enabled = true
      bind_address = "0.0.0.0"
      bind_port = "8080"
      live_path = "/live"
      ready_path = "/ready"
    }
