apiVersion: v1
kind: ServiceAccount
metadata:
  name: spire-oidc
  namespace: spire
---
apiVersion: v1
kind: Service
metadata:
  name: spire-oidc
  namespace: spire
  labels:
    app.kubernetes.io/name: spire-oidc
spec:
  selector:
    app.kubernetes.io/name: spire-oidc
  ports:
    - name: http
      port: 8082
      targetPort: http
