apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gitea
  namespace: git-mirror
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: gitea
  policyTypes: [Ingress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: argocd
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: git-mirror
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: his-hope
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
      ports:
        - protocol: TCP
          port: 3000
        - protocol: TCP
          port: 2222
