/** Read permissions for admin-app routes (client-side defense-in-depth). */
export const ADMIN_ROUTE_READ_PERMISSIONS: Readonly<Record<string, string>> = {
  "iam/overview": "admin.roles.read",
  "iam/scopes": "admin.roles.read",
  "iam/users": "admin.users.read",
  "iam/groups": "admin.roles.read",
  "iam/external-identities": "admin.roles.read",
  "iam/service-principals": "admin.roles.read",
  "iam/workload-roles": "admin.roles.read",
  "iam/clients": "admin.clients.read",
  "iam/api-audiences": "admin.roles.read",
  "iam/trusted-issuers": "admin.roles.read",
  "iam/services": "admin.roles.read",
  "iam/permission-sets": "admin.roles.read",
  "iam/policies": "admin.roles.read",
  "iam/boundaries": "admin.roles.read",
  "iam/resource-policies": "admin.roles.read",
  "iam/assignments": "admin.roles.read",
  "iam/sessions": "admin.users.read",
  "iam/workload-sessions": "admin.roles.read",
  "iam/revocations": "admin.users.read",
  "iam/analyzer/effective-access": "admin.policy.simulate",
  "iam/analyzer/policy-simulator": "admin.policy.simulate",
  "iam/analyzer/access-diff": "admin.policy.simulate",
  "iam/analyzer/unused-permissions": "admin.policy.simulate",
  "iam/audit-integrations": "admin.settings.read",
  "iam/access-requests": "admin.roles.read",
  "iam/authorization-change-requests": "admin.roles.read",
  "iam/access-reviews": "admin.roles.read",
  "iam/jit-access": "admin.roles.read",
  "iam/break-glass": "admin.roles.read",
  clients: "admin.clients.read",
  users: "admin.users.read",
  roles: "admin.roles.read",
  consents: "admin.users.read",
  "security-providers": "admin.security-signals.manage",
  "access-management": "admin.roles.read",
  "identity-capabilities": "admin.settings.read",
  "identity-operations": "admin.users.read",
  "security/identity": "admin.settings.read",
  "database-platform": "admin.settings.read",
  "mobile-operations": "admin.users.read",
};

export function resolveAdminRoutePermission(path: string): string | undefined {
  return ADMIN_ROUTE_READ_PERMISSIONS[path];
}
