import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { forkJoin } from 'rxjs';
import { HisHopeDataTableCellDirective, HisHopeDataTableColumn, HisHopeDataTableComponent, HisHopeI18nService, HisHopePageHeaderComponent, HisHopePageLayoutComponent, HisHopePermissionService, HisHopeToolbarComponent, HisHopeTranslatePipe } from '@his-hope/frontend-foundation';
import { AdminApiService, IamPermissionBoundary, IamScope, IamWorkloadRole, PermissionDefinition, User } from '../../core/services/admin-api.service';

@Component({ selector: 'app-boundaries-page', standalone: true, imports: [CommonModule, FormsModule, HisHopeDataTableCellDirective, HisHopeDataTableComponent, HisHopePageHeaderComponent, HisHopePageLayoutComponent, HisHopeToolbarComponent, HisHopeTranslatePipe], template: `
<hh-page-layout><hh-page-header hhPageHeader [title]="'admin.boundaries' | hhTranslate:'Permission boundaries'" [subtitle]="'admin.boundariesSubtitle' | hhTranslate:'Limit the maximum permissions a principal can receive.'" /><hh-toolbar hhPageToolbar [label]="'admin.boundaries' | hhTranslate:'Permission boundaries'"><span hhToolbarTitle>{{ boundaries.length }} {{ 'admin.boundaries' | hhTranslate }}</span><button *ngIf="canWrite" hhToolbarActions type="button" class="hh-button hh-button--primary" (click)="toggleForm()">{{ (formOpen ? 'admin.cancel' : 'admin.create') | hhTranslate }}</button><button hhToolbarActions type="button" class="hh-button hh-button--secondary" (click)="load()">{{ 'admin.refresh' | hhTranslate }}</button></hh-toolbar>
<form *ngIf="canWrite && formOpen" class="hh-form-card" (ngSubmit)="save()"><div class="hh-form-grid"><label>{{ 'admin.principalType' | hhTranslate }}<select name="principalType" [(ngModel)]="draft.principalType"><option value="human">Human</option><option value="workload">Workload</option></select></label><label>{{ 'admin.principalId' | hhTranslate }}<select name="principalId" [(ngModel)]="draft.principalId" required><option value="">{{ 'admin.select' | hhTranslate }}</option><ng-container [ngSwitch]="draft.principalType"><ng-container *ngSwitchCase="'human'"><option *ngFor="let user of users" [value]="user.id">{{ user.email || user.userName }}</option></ng-container><ng-container *ngSwitchCase="'workload'"><option *ngFor="let role of workloadRoles" [value]="role.id">{{ role.key }}</option></ng-container></ng-container></select></label><label>{{ 'admin.scopeId' | hhTranslate }}<select name="scopeId" [(ngModel)]="draft.scopeId" required><option value="">{{ 'admin.select' | hhTranslate }}</option><option *ngFor="let scope of scopes" [value]="scope.id">{{ scope.key }}</option></select></label><label>{{ 'admin.permissions' | hhTranslate }}<select name="allowedPermissions" [(ngModel)]="draft.allowedPermissions" multiple size="6" required><option *ngFor="let permission of permissionsCatalog" [value]="permission.code">{{ permission.code }} · {{ permission.name }}</option></select></label><label>{{ 'admin.resourceConstraints' | hhTranslate }}<textarea name="resourceConstraintsJson" rows="3" [(ngModel)]="draft.resourceConstraintsJson" required></textarea></label></div><button class="hh-button hh-button--primary" type="submit" [disabled]="saving">{{ 'admin.save' | hhTranslate }}</button></form><div *ngIf="error" class="hh-state hh-state--error" role="alert">{{ error }}</div>
<hh-data-table [label]="'admin.boundaries' | hhTranslate:'Permission boundaries'" [columns]="columns" [rows]="rows" [loading]="loading" [empty]="!loading && !error && !rows.length"><ng-template hhDataTableCell="actions" let-row><button *ngIf="canWrite && row['isActive']" type="button" class="hh-icon-button hh-icon-button--small hh-icon-button--danger" (click)="toggle(row)" [attr.aria-label]="'admin.deactivate' | hhTranslate" [attr.title]="'admin.deactivate' | hhTranslate"><span class="material-icons" aria-hidden="true">toggle_off</span></button><button *ngIf="canWrite && !row['isActive']" type="button" class="hh-icon-button hh-icon-button--small" (click)="toggle(row)" [attr.aria-label]="'admin.activate' | hhTranslate" [attr.title]="'admin.activate' | hhTranslate"><span class="material-icons" aria-hidden="true">toggle_on</span></button></ng-template></hh-data-table></hh-page-layout>` })
export class BoundariesPageComponent implements OnInit {
  private readonly api = inject(AdminApiService); private readonly permissions = inject(HisHopePermissionService); private readonly i18n = inject(HisHopeI18nService);
  get canWrite(): boolean { return this.permissions.has('admin.roles.write'); }
  boundaries: IamPermissionBoundary[] = []; scopes: IamScope[] = []; users: User[] = []; workloadRoles: IamWorkloadRole[] = []; permissionsCatalog: PermissionDefinition[] = []; rows: Record<string, unknown>[] = []; loading = false; saving = false; error = ''; formOpen = false;
  draft = { principalType: 'human', principalId: '', scopeId: '', allowedPermissions: [] as string[], resourceConstraintsJson: '{}' };
  get columns(): HisHopeDataTableColumn[] { this.i18n.locale(); return [{ key: 'principalType', label: this.i18n.t('admin.principalType', 'Principal type') }, { key: 'principalId', label: this.i18n.t('admin.principalId', 'Principal') }, { key: 'scopeId', label: this.i18n.t('admin.scopeId', 'Scope') }, { key: 'isActive', label: this.i18n.t('admin.active', 'Active') }, { key: 'actions', label: this.i18n.t('admin.actions', 'Actions'), sortable: false, hideable: false }]; }
  ngOnInit(): void { this.load(); }
  load(): void { this.loading = true; this.error = ''; forkJoin({ boundaries: this.api.getIamBoundaries(), scopes: this.api.getIamScopes(), users: this.api.getUsers(), workloadRoles: this.api.getIamWorkloadRoles(), permissions: this.api.getPermissions() }).subscribe({ next: x => { this.boundaries = x.boundaries; this.scopes = x.scopes; this.users = x.users; this.workloadRoles = x.workloadRoles; this.permissionsCatalog = x.permissions.filter(item => !item.isDeprecated); this.rows = x.boundaries.map(item => ({ ...item })); }, error: () => { this.error = this.i18n.t('admin.iamLoadFailed', 'Unable to load boundaries.'); this.loading = false; }, complete: () => this.loading = false }); }
  toggleForm(): void { if (!this.canWrite) return; this.formOpen = !this.formOpen; this.draft = { principalType: 'human', principalId: '', scopeId: this.scopes.find(x => x.isActive)?.id ?? '', allowedPermissions: [], resourceConstraintsJson: '{}' }; }
  save(): void { if (!this.canWrite || !this.draft.principalId || !this.draft.scopeId || !this.draft.allowedPermissions.length) return; this.saving = true; this.api.createIamBoundary({ principalType: this.draft.principalType, principalId: this.draft.principalId, scopeId: this.draft.scopeId, allowedPermissions: this.draft.allowedPermissions, resourceConstraintsJson: this.draft.resourceConstraintsJson }).subscribe({ next: () => { this.formOpen = false; this.load(); }, error: () => { this.error = this.i18n.t('admin.iamSaveFailed', 'Unable to create boundary.'); this.saving = false; }, complete: () => this.saving = false }); }
  toggle(row: Record<string, unknown>): void { if (!this.canWrite) return; const id = String(row['id'] ?? ''); const call = row['isActive'] ? this.api.deactivateIamBoundary(id) : this.api.activateIamBoundary(id); call.subscribe({ next: () => this.load(), error: () => this.error = this.i18n.t('admin.iamSaveFailed', 'Unable to update boundary.') }); }
}
