apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-autoscaler-config
  namespace: kube-system
data:
  values: |
    autoDiscovery:
      clusterName: his-hope-us-east1
    awsRegion: us-east-1
    podAnnotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
    scaleDownEnabled: true
    scaleDownDelayAfterAdd: 10m
    scaleDownDelayAfterDelete: 10m
    scaleDownDelayAfterFailure: 10m
    scaleDownUnneededTime: 10m
    scaleDownUnreadyTime: 20m
    maxNodeProvisionTime: 15m
    maxEmptyBulkDelete: 10
