---
- name: Install keepalived
  ansible.builtin.package:
    name: keepalived
    state: present

- name: Install K3s VIP keepalived configuration
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0600'
  no_log: true
  notify: Restart keepalived

- name: Enable keepalived
  ansible.builtin.systemd_service:
    name: keepalived
    enabled: true
    state: started
