namespace His.Hope.Contracts.Manufacturing;

public sealed record CreateLotRequest(string TenantKey, string Sku, decimal Quantity, string Uom, string Disposition = "Released", DateOnly? BestBefore = null);
public sealed record CreateTransformationRequest(string TenantKey, string OutputSku, decimal OutputQuantity, string OutputUom, IReadOnlyList<TransformationInput> Inputs, string ProcessStep = "production", Guid? RecipeId = null, Guid? MachineId = null);
public sealed record TransformationInput(Guid LotId, decimal Quantity, Guid? ReservationId = null);
public sealed record LotDto(Guid Id, string TenantKey, string Sku, decimal Quantity, string Uom, string Disposition, DateOnly? BestBefore, DateTimeOffset CreatedAt);
public sealed record TransformationDto(Guid Id, string TenantKey, string ProcessStep, Guid? RecipeId, Guid? MachineId, IReadOnlyList<TransformationInput> Inputs, LotDto Output, decimal InputQuantity, decimal YieldPercent, decimal LossQuantity, DateTimeOffset CreatedAt);
public sealed record GenealogyDto(LotDto Lot, IReadOnlyList<LotRelationDto> Relations);
public sealed record LotRelationDto(Guid TransformationId, Guid LotId, string Sku, string Role, decimal Quantity);
public sealed record AvailabilityDto(string TenantKey, string Sku, decimal ReleasedQuantity, string Uom, DateTimeOffset AsOf);
public sealed record ManufacturingDashboardSummaryDto(string TenantKey, int LotCount, decimal ReleasedQuantity, decimal QuarantinedQuantity, int TransformationCount, decimal AverageYieldPercent, decimal TotalLossQuantity, int OpenProductionOrderCount, int ActiveBatchCount, int PendingInspectionCount, int FailedInspectionCount, DateTimeOffset AsOf);
public sealed record EventReceiptDto(Guid Id, string EventType, string AggregateId, DateTime ReceivedAt);
public sealed record TransformationSummaryDto(Guid Id, string TenantKey, string ProcessStep, Guid? RecipeId, Guid? MachineId, Guid OutputLotId, decimal InputQuantity, decimal OutputQuantity, decimal YieldPercent, decimal LossQuantity, DateTimeOffset CreatedAt);
public sealed record LotDispositionRequest(string Disposition);
public sealed record CreateQualityInspectionRequest(Guid LotId, string TenantKey, string Status, decimal MoisturePercent, string Inspector, string? Notes = null, DateTimeOffset? InspectedAt = null);
public sealed record QualityInspectionDto(Guid Id, Guid LotId, string TenantKey, string Status, decimal MoisturePercent, string Inspector, string? Notes, DateTimeOffset InspectedAt);
public sealed record CreateRecipeRequest(string TenantKey, string ProductSku, int Version, string ProcessStep, string OutputUom, decimal TargetYieldPercent, IReadOnlyList<RecipeComponentRequest>? Components = null, bool Active = true);
public sealed record RecipeComponentRequest(string IngredientSku, decimal Quantity, string Uom);
public sealed record RecipeDto(Guid Id, string TenantKey, string ProductSku, int Version, string ProcessStep, string OutputUom, decimal TargetYieldPercent, bool Active, IReadOnlyList<RecipeComponentDto> Components, DateTimeOffset CreatedAt);
public sealed record RecipeComponentDto(string IngredientSku, decimal Quantity, string Uom);
public sealed record CreateMachineRequest(string TenantKey, string Code, string Name, string Status = "Available", DateTimeOffset? LastMaintenanceAt = null, DateTimeOffset? NextMaintenanceAt = null, bool Active = true);
public sealed record RecordMaintenanceRequest(DateTimeOffset MaintainedAt, DateTimeOffset? NextMaintenanceAt, string Status = "Available");
public sealed record MachineDto(Guid Id, string TenantKey, string Code, string Name, string Status, DateTimeOffset? LastMaintenanceAt, DateTimeOffset? NextMaintenanceAt, bool Active, DateTimeOffset CreatedAt);
public sealed record CreateProductionOrderRequest(string OrderNumber, string ProductSku, Guid RecipeId, decimal TargetQuantity, string OutputUom);
public sealed record ProductionOrderDto(Guid Id, string TenantKey, string OrderNumber, string ProductSku, Guid RecipeId, int RecipeVersion, decimal TargetQuantity, string OutputUom, string Status, DateTimeOffset CreatedAt, DateTimeOffset? ReleasedAt);
public sealed record CreateProductionBatchRequest(Guid ProductionOrderId, string BatchNumber, decimal? PlannedQuantity = null, Guid? MachineId = null);
public sealed record ProductionBatchDto(Guid Id, string TenantKey, Guid ProductionOrderId, string BatchNumber, string Status, decimal PlannedQuantity, decimal ActualOutputQuantity, Guid? MachineId, DateTimeOffset CreatedAt, DateTimeOffset? StartedAt, DateTimeOffset? CompletedAt, IReadOnlyList<OperationExecutionDto> Operations);
public sealed record RecordOperationRequest(int Sequence, string ProcessStep, string Operator, decimal InputQuantity, decimal OutputQuantity, bool Required = true, string QcStatus = "Pending", DateTimeOffset? StartedAt = null);
public sealed record OperationExecutionDto(Guid Id, Guid ProductionBatchId, int Sequence, string ProcessStep, string Operator, decimal InputQuantity, decimal OutputQuantity, decimal LossQuantity, string Status, bool Required, string QcStatus, DateTimeOffset? StartedAt, DateTimeOffset? CompletedAt);
public sealed record CreateLotReservationRequest(string ReferenceType, Guid ReferenceId, decimal Quantity, string? FacilityId = null, DateTimeOffset? ExpiresAt = null);
public sealed record LotReservationDto(Guid Id, string TenantKey, Guid LotId, string ReferenceType, Guid ReferenceId, decimal Quantity, string Uom, string Status, DateTimeOffset CreatedAt, DateTimeOffset? ExpiresAt);
public sealed record FefoLotDto(Guid LotId, string Sku, decimal Quantity, decimal ReservedQuantity, decimal AvailableQuantity, string Uom, DateOnly? BestBefore, DateTimeOffset CreatedAt);
public sealed record CreateSupplierRequest(string TenantKey, string Code, string Name, bool Active = true);
public sealed record SupplierDto(Guid Id, string TenantKey, string Code, string Name, bool Active, DateTimeOffset CreatedAt);
public sealed record CreatePurchaseOrderRequest(string TenantKey, Guid SupplierId, string OrderNumber, string Currency, IReadOnlyList<PurchaseOrderLineRequest> Lines, string Status = "Draft", DateTimeOffset? OrderedAt = null, DateTimeOffset? ExpectedAt = null);
public sealed record PurchaseOrderLineRequest(string MaterialSku, decimal OrderedQuantity, string Uom, decimal UnitPrice);
public sealed record PurchaseOrderDto(Guid Id, string TenantKey, string OrderNumber, Guid SupplierId, string SupplierCode, string Status, string Currency, DateTimeOffset OrderedAt, DateTimeOffset? ExpectedAt, IReadOnlyList<PurchaseOrderLineDto> Lines);
public sealed record PurchaseOrderLineDto(Guid Id, string MaterialSku, decimal OrderedQuantity, decimal ReceivedQuantity, string Uom, decimal UnitPrice);
public sealed record ReceiveInboundLotRequest(Guid PurchaseOrderId, Guid PurchaseOrderLineId, string MaterialSku, string ReceiptNumber, string SupplierLotCode, string FacilityId, decimal Quantity, DateOnly? ExpiryDate = null, DateTimeOffset? ReceivedAt = null);
public sealed record InboundReceiptDto(Guid Id, string TenantKey, string ReceiptNumber, Guid PurchaseOrderId, Guid PurchaseOrderLineId, Guid LotId, Guid SupplierId, string SupplierLotCode, string FacilityId, decimal Quantity, string Uom, DateTimeOffset ReceivedAt, string Disposition, DateOnly? ExpiryDate);
public sealed record CostProjectionDto(string TenantKey, Guid RecipeId, string ProductSku, int RecipeVersion, string OutputUom, decimal PlannedOutputQuantity, decimal TargetYieldPercent, decimal ProjectedLossQuantity, decimal EstimatedMaterialCost, decimal EstimatedMaterialCostPerOutputUnit, IReadOnlyList<CostProjectionComponentDto> Components, IReadOnlyList<string> MissingPriceSkus, DateTimeOffset GeneratedAt);
public sealed record CostProjectionComponentDto(string IngredientSku, string Uom, decimal RequiredInputQuantity, decimal EstimatedUnitPrice, decimal EstimatedCost, bool HasPrice);
public sealed record InventoryTransactionDto(Guid Id, string TenantKey, Guid LotId, string TransactionType, decimal Quantity, string Uom, string FacilityId, string StockStatus, Guid CorrelationId, DateTimeOffset OccurredAt);
