import { DatePipe } from "@angular/common";
import { FormsModule } from "@angular/forms";
import { ChangeDetectionStrategy, ChangeDetectorRef, Component, DestroyRef, OnInit, inject } from "@angular/core";
import { takeUntilDestroyed } from "@angular/core/rxjs-interop";
import { HisHopeActionButtonComponent, HisHopePageHeaderComponent, HisHopePageLayoutComponent, HisHopeStateComponent } from "@his-hope/frontend-foundation/ui";
import { HisHopeApiErrorMessageService as ApiErrorMessageService, HisHopeI18nService, HisHopeTranslatePipe } from "@his-hope/frontend-foundation/i18n";
import { HisHopeCapaDto, HisHopeSupplierDto, HisHopeSupplierEvaluationDto } from "@his-hope/frontend-foundation/contracts";
import { ManufacturingApiService } from "../../core/services/manufacturing-api.service";
import { TenantContextService } from "../../core/services/tenant-context.service";

@Component({ standalone: true, changeDetection: ChangeDetectionStrategy.OnPush, imports: [DatePipe, FormsModule, HisHopeActionButtonComponent, HisHopePageHeaderComponent, HisHopePageLayoutComponent, HisHopeStateComponent, HisHopeTranslatePipe], template: `
<hh-page-layout><hh-page-header hhPageHeader [title]="'customerPortal.capas' | hhTranslate: 'CAPA & supplier evaluation'" [subtitle]="subtitle" />
@if (loading) { <hh-state kind="loading" [message]="'customerPortal.loadingCapas' | hhTranslate: 'Loading CAPA…'" /> } @else {
<section class="section"><h2>{{ 'customerPortal.createCapa' | hhTranslate: 'Create CAPA' }}</h2><form class="form" (ngSubmit)="create()"><label>{{ 'customerPortal.capaTitle' | hhTranslate: 'Title' }}<input name="title" [(ngModel)]="draft.title" required /></label><label>{{ 'customerPortal.capaOwner' | hhTranslate: 'Owner' }}<input name="owner" [(ngModel)]="draft.owner" required /></label><label class="wide">{{ 'customerPortal.capaProblem' | hhTranslate: 'Problem' }}<textarea name="problem" [(ngModel)]="draft.problemDescription" required></textarea></label><label class="wide">{{ 'customerPortal.capaRootCause' | hhTranslate: 'Root cause' }}<textarea name="rootCause" [(ngModel)]="draft.rootCause"></textarea></label><label class="wide">{{ 'customerPortal.capaCorrectiveAction' | hhTranslate: 'Corrective action' }}<textarea name="corrective" [(ngModel)]="draft.correctiveAction"></textarea></label><label class="wide">{{ 'customerPortal.capaPreventiveAction' | hhTranslate: 'Preventive action' }}<textarea name="preventive" [(ngModel)]="draft.preventiveAction"></textarea></label><div class="wide actions"><hh-action-button type="submit" kind="primary" icon="add_task" [label]="'customerPortal.createCapa' | hhTranslate: 'Create CAPA'" [disabled]="saving" /></div></form>@if (error) { <p class="error">{{ error }}</p> }</section>
<section class="section"><h2>{{ 'customerPortal.supplierEvaluation' | hhTranslate: 'Supplier evaluation' }}</h2><form class="form"><label>{{ 'customerPortal.supplier' | hhTranslate: 'Supplier' }}<select name="evaluationSupplier" [(ngModel)]="evaluation.supplierId"><option value="">{{ 'customerPortal.selectSupplier' | hhTranslate: 'Select supplier' }}</option>@for (supplier of suppliers; track supplier.id) { <option [value]="supplier.id">{{ supplier.code }} · {{ supplier.name }}</option> }</select></label><label>{{ 'customerPortal.scoreRange' | hhTranslate: 'Score (1–5)' }}<input name="evaluationScore" type="number" min="1" max="5" [(ngModel)]="evaluation.score" /></label><label class="wide">{{ 'customerPortal.notes' | hhTranslate: 'Notes' }}<textarea name="evaluationNotes" [(ngModel)]="evaluation.notes"></textarea></label><div class="wide actions"><hh-action-button type="button" kind="secondary" icon="star_rate" [label]="'customerPortal.saveEvaluation' | hhTranslate: 'Save evaluation'" [disabled]="saving" (pressed)="evaluate()" /></div></form>@if (evaluations.length) { <ul class="list">@for (item of evaluations; track item.id) { <li>{{ supplierName(item.supplierId) }} · {{ item.score }}/5 · {{ item.evaluatedAt | date:'medium' }}</li> }</ul> }</section>
<section class="grid">@for (capa of capas; track capa.id) { <article class="card"><header><strong>{{ capa.title }}</strong><span class="status">{{ capa.status }}</span></header><p>{{ capa.problemDescription }}</p><p class="meta">{{ 'customerPortal.capaOwner' | hhTranslate: 'Owner' }}: {{ capa.owner }} · {{ capa.createdAt | date:'medium' }}</p><div class="actions">@if (capa.status === 'Open') { <hh-action-button kind="secondary" icon="play_arrow" [label]="'customerPortal.start' | hhTranslate: 'Start'" (pressed)="status(capa, 'InProgress')" /> } @if (capa.status === 'InProgress') { <hh-action-button kind="secondary" icon="verified" [label]="'customerPortal.verify' | hhTranslate: 'Verify'" (pressed)="status(capa, 'Verified')" /> } @if (capa.status === 'Verified') { <hh-action-button kind="primary" icon="done_all" [label]="'customerPortal.close' | hhTranslate: 'Close'" (pressed)="status(capa, 'Closed')" /> }</div></article> } @empty { <p class="empty">{{ 'customerPortal.noCapaRecords' | hhTranslate: 'No CAPA records.' }}</p> }</section> }</hh-page-layout>`, styles: [`:host{font-family:var(--font-sans)}.section{margin-bottom:var(--space-lg)}.form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:var(--space-md);padding:var(--space-md);background:var(--surface-muted);border-radius:var(--radius-card)}label{display:grid;gap:var(--space-2xs);color:var(--text-primary)}input,select,textarea{border:1px solid var(--border-subtle);border-radius:var(--radius-control);padding:var(--space-sm);background:var(--surface);color:var(--text-primary);font:inherit}.wide{grid-column:1/-1}.actions{display:flex;gap:var(--space-sm);justify-content:flex-end}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(320px,1fr));gap:var(--space-md)}.card{padding:var(--space-md);border:1px solid var(--border-subtle);border-radius:var(--radius-card);background:var(--surface);color:var(--text-primary)}header{display:flex;justify-content:space-between;gap:var(--space-md)}.status{padding:var(--space-2xs) var(--space-sm);background:var(--surface-muted);border-radius:var(--radius-badge)}.meta{color:var(--text-secondary)}.error{color:var(--color-danger)}.list{padding:0;list-style:none}.list li{padding:var(--space-sm) 0;border-bottom:1px solid var(--border-subtle)}@media(max-width:700px){.form{grid-template-columns:1fr}.wide{grid-column:auto}}`] })
export class CapasPageComponent implements OnInit {
  private readonly api = inject(ManufacturingApiService); private readonly tenantContext = inject(TenantContextService); private readonly i18n = inject(HisHopeI18nService); private readonly errors = inject(ApiErrorMessageService); private readonly cdr = inject(ChangeDetectorRef); private readonly destroyRef = inject(DestroyRef);
  capas: HisHopeCapaDto[] = []; suppliers: HisHopeSupplierDto[] = []; evaluations: HisHopeSupplierEvaluationDto[] = []; loading = true; saving = false; error = ""; tenantLabel: string | null = null; actor = "operator"; draft = { title: "", problemDescription: "", rootCause: "", correctiveAction: "", preventiveAction: "", owner: "operator" }; evaluation = { supplierId: "", score: 5, notes: "" };
  get subtitle(): string { this.i18n.locale(); return this.i18n.t("customerPortal.tenantScope", "Tenant: {{tenant}}", { tenant: this.tenantLabel ?? "—" }); }
  supplierName(id: string): string { return this.suppliers.find((supplier) => supplier.id === id)?.name ?? id; }
  ngOnInit(): void { this.tenantContext.activeTenantLabel$.pipe(takeUntilDestroyed(this.destroyRef)).subscribe((x) => { this.tenantLabel = x; this.cdr.markForCheck(); }); this.tenantContext.activeTenantKey$.pipe(takeUntilDestroyed(this.destroyRef)).subscribe(() => this.load()); }
  load(): void { this.loading = true; this.api.getCapas().pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: (items) => { this.capas = items ?? []; this.api.getSuppliers().pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: (suppliers) => { this.suppliers = suppliers ?? []; this.api.getSupplierEvaluations().pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: (evaluations) => { this.evaluations = evaluations ?? []; this.loading = false; this.cdr.markForCheck(); }, error: () => { this.loading = false; this.cdr.markForCheck(); } }); }, error: () => { this.loading = false; this.cdr.markForCheck(); } }); }, error: (e) => { this.error = this.errors.message(e, "customerPortal.capasLoadFailed"); this.loading = false; this.cdr.markForCheck(); } }); }
  create(): void { if (!this.draft.title.trim() || !this.draft.problemDescription.trim() || !this.draft.owner.trim()) return; this.saving = true; this.api.createCapa(this.draft).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: () => { this.saving = false; this.draft = { title: "", problemDescription: "", rootCause: "", correctiveAction: "", preventiveAction: "", owner: this.actor }; this.load(); }, error: (e) => { this.error = this.errors.message(e, "customerPortal.capaSaveFailed"); this.saving = false; this.cdr.markForCheck(); } }); }
  status(capa: HisHopeCapaDto, next: string): void { this.saving = true; this.api.updateCapaStatus(capa.id, next, this.actor).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: () => { this.saving = false; this.load(); }, error: (e) => { this.error = this.errors.message(e, "customerPortal.capaStatusFailed"); this.saving = false; this.cdr.markForCheck(); } }); }
  evaluate(): void { if (!this.evaluation.supplierId || this.evaluation.score < 1 || this.evaluation.score > 5) return; this.saving = true; this.api.createSupplierEvaluation({ supplierId: this.evaluation.supplierId, score: this.evaluation.score, notes: this.evaluation.notes }).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: (item) => { this.evaluations = [item, ...this.evaluations]; this.saving = false; this.cdr.markForCheck(); }, error: (e) => { this.error = this.errors.message(e, "customerPortal.supplierEvaluationFailed"); this.saving = false; this.cdr.markForCheck(); } }); }
}
