apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: spire-oidc
  namespace: spire
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spire-oidc
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: minio
  namespace: backup
spec:
  minAvailable: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
