apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../spire
  - ../../production-ha

components:
  - ../prod/image-digests

patches:
  - path: spire-server-ha-patch.yaml
  - path: spire-server-production-datastore-patch.yaml
