// <auto-generated />
using System;
using His.Hope.PharmacyService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace His.Hope.PharmacyService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PharmacyDbContext))]
    partial class PharmacyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("His.Hope.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CausationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("causation_id");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("claimed_by");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeadLetteredOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dead_lettered_on");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastRetryOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_retry_on");

                    b.Property<DateTime?>("LockExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lock_expires_at");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Status", "OccurredOn");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("His.Hope.PharmacyService.Domain.Aggregates.Medication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BrandName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("brandname");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("DosageForm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("dosageform");

                    b.Property<string>("FacilityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("facilityid");

                    b.Property<string>("GenericName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("genericname");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<bool>("RequiresPrescription")
                        .HasColumnType("boolean")
                        .HasColumnName("requiresprescription");

                    b.Property<string>("Route")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("route");

                    b.Property<string>("Strength")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("strength");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.HasIndex("GenericName");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.ToTable("medications", null, t =>
                        {
                            t.Property("BrandName")
                                .HasColumnName("brand_name");

                            t.Property("CreatedAt")
                                .HasColumnName("created_at");

                            t.Property("DosageForm")
                                .HasColumnName("dosage_form");

                            t.Property("FacilityId")
                                .HasColumnName("facility_id");

                            t.Property("GenericName")
                                .HasColumnName("generic_name");

                            t.Property("IsActive")
                                .HasColumnName("is_active");

                            t.Property("RequiresPrescription")
                                .HasColumnName("requires_prescription");

                            t.Property("UpdatedAt")
                                .HasColumnName("updated_at");
                        });

                    b.HasAnnotation("HisHope:SoftDelete", true);
                });

            modelBuilder.Entity("His.Hope.PharmacyService.Domain.Aggregates.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancellationreason");

                    b.Property<DateTime?>("CancelledDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelleddate");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("DosageForm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("dosageform");

                    b.Property<string>("DosageInstructions")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("dosageinstructions");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expirydate");

                    b.Property<string>("FacilityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("facilityid");

                    b.Property<DateTime?>("FilledDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("filleddate");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid?>("MedicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("medicationid");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("medicationname");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patientid");

                    b.Property<DateTime>("PrescribedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("prescribeddate");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("providerid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("Refills")
                        .HasColumnType("integer")
                        .HasColumnName("refills");

                    b.Property<string>("Route")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("route");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Strength")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("strength");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PrescribedDate");

                    b.HasIndex("ProviderId");

                    b.HasIndex("Status");

                    b.HasIndex("PatientId", "PrescribedDate")
                        .HasDatabaseName("IX_Prescriptions_Patient_Date_Id");

                    b.HasIndex("FacilityId", "Status", "PrescribedDate")
                        .HasDatabaseName("IX_Prescriptions_Facility_Status_Date_Id");

                    b.ToTable("prescriptions", null, t =>
                        {
                            t.Property("CancellationReason")
                                .HasColumnName("cancellation_reason");

                            t.Property("CancelledDate")
                                .HasColumnName("cancelled_date");

                            t.Property("CreatedAt")
                                .HasColumnName("created_at");

                            t.Property("DosageForm")
                                .HasColumnName("dosage_form");

                            t.Property("DosageInstructions")
                                .HasColumnName("dosage_instructions");

                            t.Property("ExpiryDate")
                                .HasColumnName("expiry_date");

                            t.Property("FacilityId")
                                .HasColumnName("facility_id");

                            t.Property("FilledDate")
                                .HasColumnName("filled_date");

                            t.Property("MedicationId")
                                .HasColumnName("medication_id");

                            t.Property("MedicationName")
                                .HasColumnName("medication_name");

                            t.Property("PatientId")
                                .HasColumnName("patient_id");

                            t.Property("PrescribedDate")
                                .HasColumnName("prescribed_date");

                            t.Property("ProviderId")
                                .HasColumnName("provider_id");

                            t.Property("UpdatedAt")
                                .HasColumnName("updated_at");
                        });

                    b.HasAnnotation("HisHope:SoftDelete", true);
                });
#pragma warning restore 612, 618
        }
    }
}
