CREATE TABLE "Encounters" (
    EncounterId UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    PatientId UUID NOT NULL,
    AppointmentId UUID,
    ProviderId VARCHAR(36) NOT NULL,
    EncounterDate TIMESTAMPTZ NOT NULL DEFAULT now(),
    EncounterType VARCHAR(20) NOT NULL,
    Status VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS',
    ChiefComplaint VARCHAR(1000),
    -- HPI (History of Present Illness) - Value Object inline columns
    HpiOnset VARCHAR(500),
    HpiLocation VARCHAR(500),
    HpiDuration VARCHAR(200),
    HpiCharacteristics VARCHAR(1000),
    HpiAggravatingFactors VARCHAR(1000),
    HpiRelievingFactors VARCHAR(1000),
    HpiPriorTreatments VARCHAR(1000),
    -- VitalSigns - Value Object inline columns (OwnsOne)
    Temperature DECIMAL(5,2),
    HeartRate INT,
    RespiratoryRate INT,
    SystolicBP INT,
    DiastolicBP INT,
    OxygenSaturation DECIMAL(5,2),
    HeightCm DECIMAL(6,2),
    WeightKg DECIMAL(6,2),
    Bmi DECIMAL(5,2),
    -- Additional encounter fields
    Assessment VARCHAR(5000),
    Plan VARCHAR(5000),
    DiagnosisNotes VARCHAR(5000),
    -- Audit
    CreatedAt TIMESTAMPTZ NOT NULL DEFAULT now(),
    UpdatedAt TIMESTAMPTZ
);

-- Diagnoses child table matching EF OwnsMany mapping (table: "EncounterDiagnoses")
CREATE TABLE "EncounterDiagnoses" (
    EncounterId UUID NOT NULL REFERENCES "Encounters"(EncounterId) ON DELETE CASCADE,
    Id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    ConditionName VARCHAR(500) NOT NULL,
    Icd10Code VARCHAR(20) NOT NULL,
    IsPrimary BOOL NOT NULL DEFAULT false,
    Notes VARCHAR(1000),
    PRIMARY KEY (EncounterId, Id)
);

-- Procedures child table matching EF OwnsMany mapping (table: "EncounterProcedures")
CREATE TABLE "EncounterProcedures" (
    EncounterId UUID NOT NULL REFERENCES "Encounters"(EncounterId) ON DELETE CASCADE,
    Id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    ProcedureName VARCHAR(500) NOT NULL,
    CptCode VARCHAR(20) NOT NULL,
    PerformedDate TIMESTAMPTZ NOT NULL,
    Notes VARCHAR(1000),
    PRIMARY KEY (EncounterId, Id)
);

-- Keep "Prescriptions" and "ClinicalNotes" for backward compat (referenced by encounterId)
CREATE TABLE "Prescriptions" (
    EncounterId UUID NOT NULL REFERENCES "Encounters"(EncounterId) ON DELETE CASCADE,
    PrescriptionId UUID NOT NULL DEFAULT gen_random_uuid(),
    MedicationName VARCHAR(200) NOT NULL,
    Dosage VARCHAR(100) NOT NULL,
    Frequency VARCHAR(100),
    Route VARCHAR(50),
    DurationDays INT,
    PrescribedAt TIMESTAMPTZ NOT NULL DEFAULT now(),
    PrescribedBy VARCHAR(36),
    Instructions VARCHAR(1000),
    IsActive BOOL DEFAULT true,
    PRIMARY KEY (EncounterId, PrescriptionId)
);

CREATE TABLE "ClinicalNotes" (
    EncounterId UUID NOT NULL REFERENCES "Encounters"(EncounterId) ON DELETE CASCADE,
    NoteId UUID NOT NULL DEFAULT gen_random_uuid(),
    NoteType VARCHAR(50) NOT NULL,
    Content TEXT NOT NULL,
    RecordedAt TIMESTAMPTZ NOT NULL DEFAULT now(),
    RecordedBy VARCHAR(36),
    PRIMARY KEY (EncounterId, NoteId)
);

CREATE TABLE "OutboxMessages" (
    Id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    Type VARCHAR(500) NOT NULL,
    Content JSONB NOT NULL,
    CorrelationId VARCHAR(200),
    CausationId VARCHAR(200),
    OccurredOn TIMESTAMPTZ NOT NULL DEFAULT now(),
    ProcessedOn TIMESTAMPTZ,
    Status VARCHAR(50) NOT NULL DEFAULT 'Pending',
    Error VARCHAR(1000),
    RetryCount INT DEFAULT 0,
    LastRetryOn TIMESTAMPTZ,
    LockExpiresAt TIMESTAMPTZ
);

-- Backward-compatibility for existing deployments: add VitalSigns inline columns


























