// <auto-generated />
using His.Hope.IdentityService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace His.Hope.IdentityService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260817053600_AddDirectoryProvisioningOutboxLeaseColumns")]
    partial class AddDirectoryProvisioningOutboxLeaseColumns
    {
    }
}
