apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../spire
  - ../../production-ha/spire-postgres-cluster.yaml
  - ../../production-ha/spire-postgres-network-policy.yaml
  - ../../production-ha/spire-server-pdb.yaml
  - ../../production-ha/backup-object-store.yaml
  - ../../production-ha/cnpg-barman-object-store.yaml

components:
  - ../prod/image-digests

patches:
  - path: ../../production-ha/spire-server-ha-patch.yaml
  - path: ../../production-ha/spire-server-production-datastore-patch.yaml
