using His.Hope.IdentityService.Domain.Entities;

namespace His.Hope.IdentityService.Infrastructure.Persistence;

/// <summary>
/// Baseline labels shared by the native mobile admin shell, its security screens,
/// the dashboard observability app, and the main His.Hope clinical app.
/// The catalog is deliberately keyed by feature rather than by translated text so
/// Angular and native clients can consume the same API contract.
/// </summary>
internal static class LocalizationSeedData
{
    public static readonly LocalizationResource[] Resources =
    [
        new() { Key = "mobile.nav.home", Description = "Mobile admin navigation: home" },
        new() { Key = "mobile.nav.clients", Description = "Mobile admin navigation: clients" },
        new() { Key = "mobile.nav.users", Description = "Mobile admin navigation: users" },
        new() { Key = "mobile.nav.roles", Description = "Mobile admin navigation: roles" },
        new() { Key = "mobile.nav.consents", Description = "Mobile admin navigation: consents" },
        new() { Key = "mobile.nav.settings", Description = "Mobile admin navigation: settings" },
        new() { Key = "mobile.brand.identityAdministration", Description = "Mobile admin identity service label" },
        new() { Key = "mobile.auth.signIn", Description = "Mobile admin sign in action" },
        new() { Key = "mobile.auth.signOut", Description = "Mobile admin sign out action" },
        new() { Key = "mobile.common.search", Description = "Common search action" },
        new() { Key = "mobile.common.refresh", Description = "Common refresh action" },
        new() { Key = "mobile.common.retry", Description = "Common retry action" },
        new() { Key = "mobile.common.save", Description = "Common save action" },
        new() { Key = "mobile.common.cancel", Description = "Common cancel action" },
        new() { Key = "mobile.common.delete", Description = "Common delete action" },
        new() { Key = "mobile.common.loading", Description = "Common loading state" },
        new() { Key = "mobile.common.empty", Description = "Common empty state" },
        new() { Key = "mobile.common.error", Description = "Common error state" },
        new() { Key = "mobile.common.noPermission", Description = "Common access denied state" },
        new() { Key = "mobile.mfa.title", Description = "MFA security screen title" },
        new() { Key = "mobile.mfa.createPasskey", Description = "Passkey registration action" },
        new() { Key = "mobile.mfa.verify", Description = "MFA verification action" },
        new() { Key = "mobile.mfa.passkeyRegistrationFailed", Description = "Passkey registration error" },
        new() { Key = "mobile.mfa.setupFailed", Description = "MFA setup error" },
        new() { Key = "mobile.mfa.alreadyEnabled", Description = "MFA enabled status" },
        new() { Key = "mobile.providers.ldap", Description = "LDAP directory provider" },
        new() { Key = "mobile.providers.saml", Description = "SAML identity provider" },

        // ── Dashboard shell ──────────────────────────────────────────
        new() { Key = "app.dashboard.title", Description = "Dashboard shell: app title" },
        new() { Key = "app.dashboard.toggleNav", Description = "Dashboard shell: toggle navigation" },
        new() { Key = "app.dashboard.openPalette", Description = "Dashboard shell: open command palette" },
        new() { Key = "app.dashboard.toggleTheme", Description = "Dashboard shell: toggle dark mode" },
        new() { Key = "app.dashboard.userMenu", Description = "Dashboard shell: user menu" },
        new() { Key = "app.dashboard.logout", Description = "Dashboard shell: logout" },
        new() { Key = "app.dashboard.login", Description = "Dashboard shell: login" },
        new() { Key = "app.dashboard.workspace", Description = "Dashboard shell: workspace caption" },
        new() { Key = "app.dashboard.resources", Description = "Dashboard shell: resources nav" },
        new() { Key = "app.dashboard.logs", Description = "Dashboard shell: logs nav" },
        new() { Key = "app.dashboard.traces", Description = "Dashboard shell: traces nav" },
        new() { Key = "app.dashboard.slo", Description = "Dashboard shell: SLO nav" },
        new() { Key = "app.dashboard.metrics", Description = "Dashboard shell: metrics nav" },
        new() { Key = "app.dashboard.openResources", Description = "Dashboard shell: cmd palette resources" },
        new() { Key = "app.dashboard.openLogs", Description = "Dashboard shell: cmd palette logs" },
        new() { Key = "app.dashboard.openTraces", Description = "Dashboard shell: cmd palette traces" },

        // ── Dashboard resources ──────────────────────────────────────
        new() { Key = "dashboard.resources.title", Description = "Dashboard: system resources title" },
        new() { Key = "dashboard.resources.loading", Description = "Dashboard: loading resources" },
        new() { Key = "dashboard.resources.retry", Description = "Dashboard: retry" },
        new() { Key = "dashboard.resources.refreshing", Description = "Dashboard: refreshing" },
        new() { Key = "dashboard.resources.noResources", Description = "Dashboard: no resources found" },
        new() { Key = "dashboard.resources.cards", Description = "Dashboard: cards view" },
        new() { Key = "dashboard.resources.graph", Description = "Dashboard: graph view" },
        new() { Key = "dashboard.resources.refresh", Description = "Dashboard: refresh" },
        new() { Key = "dashboard.resources.basicInfo", Description = "Dashboard: basic info" },
        new() { Key = "dashboard.resources.name", Description = "Dashboard: name" },
        new() { Key = "dashboard.resources.version", Description = "Dashboard: version" },
        new() { Key = "dashboard.resources.status", Description = "Dashboard: status" },
        new() { Key = "dashboard.resources.health", Description = "Dashboard: health" },
        new() { Key = "dashboard.resources.healthChecks", Description = "Dashboard: health checks" },
        new() { Key = "dashboard.resources.envVars", Description = "Dashboard: environment variables" },
        new() { Key = "dashboard.resources.operations", Description = "Dashboard: operations info" },
        new() { Key = "dashboard.resources.replicas", Description = "Dashboard: replicas" },
        new() { Key = "dashboard.resources.close", Description = "Dashboard: close" },
        new() { Key = "dashboard.resources.endpoints", Description = "Dashboard: endpoints" },

        // ── Dashboard graphs & timeline ──────────────────────────────
        new() { Key = "dashboard.dependencyGraph.title", Description = "Dashboard: dependency graph" },
        new() { Key = "dashboard.dependencyGraph.healthy", Description = "Dashboard: healthy" },
        new() { Key = "dashboard.dependencyGraph.degraded", Description = "Dashboard: degraded" },
        new() { Key = "dashboard.healthTimeline.title", Description = "Dashboard: health timeline" },
        new() { Key = "dashboard.healthTimeline.incidents", Description = "Dashboard: incident count" },
        new() { Key = "dashboard.healthTimeline.allHealthy", Description = "Dashboard: all healthy" },
        new() { Key = "dashboard.healthTimeline.waiting", Description = "Dashboard: waiting for data" },
        new() { Key = "dashboard.healthTimeline.healthy", Description = "Dashboard: healthy" },
        new() { Key = "dashboard.healthTimeline.degraded", Description = "Dashboard: degraded" },
        new() { Key = "dashboard.healthTimeline.down", Description = "Dashboard: down" },
        new() { Key = "dashboard.healthTimeline.unknown", Description = "Dashboard: unknown" },
        new() { Key = "dashboard.healthTimeline.incident", Description = "Dashboard: incident" },
        new() { Key = "dashboard.healthTimeline.started", Description = "Dashboard: started" },
        new() { Key = "dashboard.healthTimeline.duration", Description = "Dashboard: duration" },

        // ── Dashboard logs ───────────────────────────────────────────
        new() { Key = "dashboard.logs.pageTitle", Description = "Dashboard logs: page title" },
        new() { Key = "dashboard.logs.refresh", Description = "Dashboard logs: refresh" },
        new() { Key = "dashboard.logs.clearFilters", Description = "Dashboard logs: clear filters" },
        new() { Key = "dashboard.logs.tabSearch", Description = "Dashboard logs: search tab" },
        new() { Key = "dashboard.logs.tabStream", Description = "Dashboard logs: stream tab" },
        new() { Key = "dashboard.logs.timeRange", Description = "Dashboard logs: time range" },
        new() { Key = "dashboard.logs.service", Description = "Dashboard logs: service" },
        new() { Key = "dashboard.logs.allServices", Description = "Dashboard logs: all services" },
        new() { Key = "dashboard.logs.fullTextSearch", Description = "Dashboard logs: full text search" },
        new() { Key = "dashboard.logs.searchPlaceholder", Description = "Dashboard logs: search placeholder" },
        new() { Key = "dashboard.logs.level", Description = "Dashboard logs: level" },
        new() { Key = "dashboard.logs.searchBtn", Description = "Dashboard logs: search button" },
        new() { Key = "dashboard.logs.loading", Description = "Dashboard logs: loading" },
        new() { Key = "dashboard.logs.noLogs", Description = "Dashboard logs: no logs" },
        new() { Key = "dashboard.logs.loadMore", Description = "Dashboard logs: load more" },
        new() { Key = "dashboard.logs.retry", Description = "Dashboard logs: retry" },
        new() { Key = "dashboard.logs.time", Description = "Dashboard logs: time column" },
        new() { Key = "dashboard.logs.message", Description = "Dashboard logs: message" },
        new() { Key = "dashboard.logs.traceId", Description = "Dashboard logs: trace ID" },
        new() { Key = "dashboard.logs.spanId", Description = "Dashboard logs: span ID" },
        new() { Key = "dashboard.logs.exception", Description = "Dashboard logs: exception" },
        new() { Key = "dashboard.logs.properties", Description = "Dashboard logs: properties" },
        new() { Key = "dashboard.logs.results", Description = "Dashboard logs: results" },

        // ── Dashboard log stream ─────────────────────────────────────
        new() { Key = "dashboard.logStream.following", Description = "Dashboard stream: following" },
        new() { Key = "dashboard.logStream.realTime", Description = "Dashboard stream: real-time" },
        new() { Key = "dashboard.logStream.newRecords", Description = "Dashboard stream: new records" },
        new() { Key = "dashboard.logStream.streaming", Description = "Dashboard stream: streaming" },
        new() { Key = "dashboard.logStream.disconnected", Description = "Dashboard stream: disconnected" },
        new() { Key = "dashboard.logStream.entries", Description = "Dashboard stream: entries" },
        new() { Key = "dashboard.logStream.pause", Description = "Dashboard stream: pause" },
        new() { Key = "dashboard.logStream.start", Description = "Dashboard stream: start" },
        new() { Key = "dashboard.logStream.clear", Description = "Dashboard stream: clear" },
        new() { Key = "dashboard.logStream.autoScrollOn", Description = "Dashboard stream: auto scroll on" },
        new() { Key = "dashboard.logStream.scrollToBottom", Description = "Dashboard stream: scroll to bottom" },
        new() { Key = "dashboard.logStream.clickStartToBegin", Description = "Dashboard stream: click start" },

        // ── Dashboard metrics ────────────────────────────────────────
        new() { Key = "dashboard.metrics.pageTitle", Description = "Dashboard metrics: page title" },
        new() { Key = "dashboard.metrics.live", Description = "Dashboard metrics: live" },
        new() { Key = "dashboard.metrics.refresh", Description = "Dashboard metrics: refresh" },
        new() { Key = "dashboard.metrics.service", Description = "Dashboard metrics: service" },
        new() { Key = "dashboard.metrics.metricType", Description = "Dashboard metrics: metric type" },
        new() { Key = "dashboard.metrics.timeRange", Description = "Dashboard metrics: time range" },
        new() { Key = "dashboard.metrics.apply", Description = "Dashboard metrics: apply" },
        new() { Key = "dashboard.metrics.selectServiceHint", Description = "Dashboard metrics: select service" },
        new() { Key = "dashboard.metrics.loading", Description = "Dashboard metrics: loading" },
        new() { Key = "dashboard.metrics.retry", Description = "Dashboard metrics: retry" },
        new() { Key = "dashboard.metrics.timeRangeLabel", Description = "Dashboard metrics: time range" },
        new() { Key = "dashboard.metrics.servicesSelected", Description = "Dashboard metrics: services selected" },
        new() { Key = "dashboard.metrics.emptyState", Description = "Dashboard metrics: empty state" },
        new() { Key = "dashboard.metricsOverview.running", Description = "Dashboard metrics: running" },
        new() { Key = "dashboard.metricsOverview.stopped", Description = "Dashboard metrics: stopped" },
        new() { Key = "dashboard.metricsOverview.degraded", Description = "Dashboard metrics: degraded" },
        new() { Key = "dashboard.metricsOverview.totalServices", Description = "Dashboard metrics: total services" },

        // ── Dashboard SLO ────────────────────────────────────────────
        new() { Key = "dashboard.slo.pageTitle", Description = "Dashboard SLO: page title" },
        new() { Key = "dashboard.slo.refresh", Description = "Dashboard SLO: refresh" },
        new() { Key = "dashboard.slo.loading", Description = "Dashboard SLO: loading" },
        new() { Key = "dashboard.slo.retry", Description = "Dashboard SLO: retry" },
        new() { Key = "dashboard.slo.availability", Description = "Dashboard SLO: availability" },
        new() { Key = "dashboard.slo.errorBudget", Description = "Dashboard SLO: error budget" },
        new() { Key = "dashboard.slo.burn1h", Description = "Dashboard SLO: burn rate 1h" },
        new() { Key = "dashboard.slo.burn6h", Description = "Dashboard SLO: burn rate 6h" },
        new() { Key = "dashboard.slo.p99Latency", Description = "Dashboard SLO: p99 latency" },
        new() { Key = "dashboard.slo.latencyTrend", Description = "Dashboard SLO: latency trend" },
        new() { Key = "dashboard.slo.last24h", Description = "Dashboard SLO: last 24h" },
        new() { Key = "dashboard.slo.emptyState", Description = "Dashboard SLO: empty state" },

        // ── Dashboard traces ─────────────────────────────────────────
        new() { Key = "dashboard.traces.title", Description = "Dashboard traces: page title" },
        new() { Key = "dashboard.traces.refresh", Description = "Dashboard traces: refresh" },
        new() { Key = "dashboard.traces.loading", Description = "Dashboard traces: loading" },
        new() { Key = "dashboard.traces.retry", Description = "Dashboard traces: retry" },
        new() { Key = "dashboard.traces.emptyState", Description = "Dashboard traces: empty state" },
        new() { Key = "dashboard.traces.traceId", Description = "Dashboard traces: trace ID" },
        new() { Key = "dashboard.traces.service", Description = "Dashboard traces: service" },
        new() { Key = "dashboard.traces.operation", Description = "Dashboard traces: operation" },
        new() { Key = "dashboard.traces.duration", Description = "Dashboard traces: duration" },
        new() { Key = "dashboard.traces.spans", Description = "Dashboard traces: spans" },
        new() { Key = "dashboard.traces.startTime", Description = "Dashboard traces: start time" },
        new() { Key = "dashboard.traces.viewDetail", Description = "Dashboard traces: view detail" },
        new() { Key = "dashboard.traces.detailTitle", Description = "Dashboard traces: detail title" },
        new() { Key = "dashboard.traces.spanId", Description = "Dashboard traces: span ID" },
        new() { Key = "dashboard.traces.parentSpanId", Description = "Dashboard traces: parent" },
        new() { Key = "dashboard.traces.tags", Description = "Dashboard traces: tags" },
        new() { Key = "dashboard.traces.logs", Description = "Dashboard traces: logs" },
        new() { Key = "dashboard.traces.back", Description = "Dashboard traces: back" },

        // ── Dashboard alerts ─────────────────────────────────────────
        new() { Key = "dashboard.alerts.critical", Description = "Dashboard alerts: critical" },
        new() { Key = "dashboard.alerts.warning", Description = "Dashboard alerts: warning" },
        new() { Key = "dashboard.alerts.info", Description = "Dashboard alerts: info" },
        new() { Key = "dashboard.alerts.systemAlerts", Description = "Dashboard alerts: system alerts" },
        new() { Key = "dashboard.alerts.noAlerts", Description = "Dashboard alerts: no alerts" },
        new() { Key = "dashboard.alerts.criticalAlert", Description = "Dashboard alerts: critical alert" },
        new() { Key = "dashboard.alerts.view", Description = "Dashboard alerts: view" },

        // ── Dashboard time ───────────────────────────────────────────
        new() { Key = "dashboard.time.minutesAgo", Description = "Dashboard time: minutes ago" },
        new() { Key = "dashboard.time.hoursAgo", Description = "Dashboard time: hours ago" },
        new() { Key = "dashboard.time.daysAgo", Description = "Dashboard time: days ago" },
        new() { Key = "dashboard.time.ago", Description = "Dashboard time: ago" },

        // ── Dashboard auth ───────────────────────────────────────────
        new() { Key = "dashboard.auth.completingSignIn", Description = "Dashboard auth: completing sign in" },

        // ── His-Hope app shell ───────────────────────────────────────
        new() { Key = "app.hishope.title", Description = "His-Hope shell: app title" },
        new() { Key = "app.navigation.openMenu", Description = "His-Hope shell: open menu" },
        new() { Key = "app.navigation.changed", Description = "His-Hope shell: navigation changed" },
        new() { Key = "app.theme.toggle", Description = "His-Hope shell: toggle theme" },

        // ── Operator mobile ────────────────────────────────────────
        new() { Key = "mobile.operatorFieldOperations", Description = "Operator shell title" },
        new() { Key = "mobile.operatorOnline", Description = "Operator online status" },
        new() { Key = "mobile.operatorTenant", Description = "Operator tenant label" },
        new() { Key = "mobile.operatorNoTenantClaim", Description = "Operator missing tenant claim" },
        new() { Key = "mobile.operatorIdentity", Description = "Operator identity label" },
        new() { Key = "mobile.operatorProduction", Description = "Operator production navigation" },
        new() { Key = "mobile.operatorTraceability", Description = "Operator traceability navigation" },
        new() { Key = "mobile.operatorQuality", Description = "Operator quality navigation" },
        new() { Key = "mobile.operatorMaintenance", Description = "Operator maintenance navigation" },
        new() { Key = "mobile.operatorSync", Description = "Operator sync navigation" },
        new() { Key = "mobile.operatorAccountMenu", Description = "Operator account menu" },
        new() { Key = "mobile.operatorProductionTitle", Description = "Operator production title" },
        new() { Key = "mobile.operatorProductionDescription", Description = "Operator production description" },
        new() { Key = "mobile.operatorBatch", Description = "Operator batch label" },
        new() { Key = "mobile.operatorChooseBatch", Description = "Operator batch selector" },
        new() { Key = "mobile.operatorOutputQuantity", Description = "Operator output quantity" },
        new() { Key = "mobile.operatorRecordOperation", Description = "Operator record operation action" },
        new() { Key = "mobile.operatorMaintenanceEyebrow", Description = "Operator maintenance eyebrow" },
        new() { Key = "mobile.operatorMaintenanceTitle", Description = "Operator maintenance title" },
        new() { Key = "mobile.operatorMaintenanceDescription", Description = "Operator maintenance description" },
        new() { Key = "mobile.operatorMachineId", Description = "Operator machine identifier" },
        new() { Key = "mobile.operatorWorkOrderId", Description = "Operator work order identifier" },
        new() { Key = "mobile.operatorTechnician", Description = "Operator technician label" },
        new() { Key = "mobile.operatorIsolationChecklist", Description = "Operator isolation checklist" },
        new() { Key = "mobile.operatorCompleteWorkOrder", Description = "Operator complete work order action" },
        new() { Key = "mobile.operatorQualityEyebrow", Description = "Operator quality eyebrow" },
        new() { Key = "mobile.operatorQualityTitle", Description = "Operator quality title" },
        new() { Key = "mobile.operatorQualityDescription", Description = "Operator quality description" },
        new() { Key = "mobile.operatorLotId", Description = "Operator lot identifier" },
        new() { Key = "mobile.operatorLotPlaceholder", Description = "Operator lot placeholder" },
        new() { Key = "mobile.operatorInspector", Description = "Operator inspector label" },
        new() { Key = "mobile.operatorInspectorPlaceholder", Description = "Operator inspector placeholder" },
        new() { Key = "mobile.operatorMoisture", Description = "Operator moisture label" },
        new() { Key = "mobile.operatorStatus", Description = "Operator status label" },
        new() { Key = "mobile.operatorSaveInspection", Description = "Operator save inspection action" },
    ];

    public static readonly LocalizationTranslation[] Translations =
    [
        new() { ResourceKey = "mobile.nav.home", Locale = "vi-VN", Value = "Trang chủ" },
        new() { ResourceKey = "mobile.nav.home", Locale = "en-US", Value = "Home" },
        new() { ResourceKey = "mobile.nav.clients", Locale = "vi-VN", Value = "Ứng dụng" },
        new() { ResourceKey = "mobile.nav.clients", Locale = "en-US", Value = "Clients" },
        new() { ResourceKey = "mobile.nav.users", Locale = "vi-VN", Value = "Người dùng" },
        new() { ResourceKey = "mobile.nav.users", Locale = "en-US", Value = "Users" },
        new() { ResourceKey = "mobile.nav.roles", Locale = "vi-VN", Value = "Vai trò" },
        new() { ResourceKey = "mobile.nav.roles", Locale = "en-US", Value = "Roles" },
        new() { ResourceKey = "mobile.nav.consents", Locale = "vi-VN", Value = "Chấp thuận" },
        new() { ResourceKey = "mobile.nav.consents", Locale = "en-US", Value = "Consents" },
        new() { ResourceKey = "mobile.nav.settings", Locale = "vi-VN", Value = "Cài đặt" },
        new() { ResourceKey = "mobile.nav.settings", Locale = "en-US", Value = "Settings" },
        new() { ResourceKey = "mobile.brand.identityAdministration", Locale = "vi-VN", Value = "QUẢN TRỊ DANH TÍNH" },
        new() { ResourceKey = "mobile.brand.identityAdministration", Locale = "en-US", Value = "IDENTITY ADMINISTRATION" },
        new() { ResourceKey = "mobile.auth.signIn", Locale = "vi-VN", Value = "Đăng nhập" },
        new() { ResourceKey = "mobile.auth.signIn", Locale = "en-US", Value = "Sign in" },
        new() { ResourceKey = "mobile.auth.signOut", Locale = "vi-VN", Value = "Đăng xuất" },
        new() { ResourceKey = "mobile.auth.signOut", Locale = "en-US", Value = "Sign out" },
        new() { ResourceKey = "mobile.common.search", Locale = "vi-VN", Value = "Tìm kiếm" },
        new() { ResourceKey = "mobile.common.search", Locale = "en-US", Value = "Search" },
        new() { ResourceKey = "mobile.common.refresh", Locale = "vi-VN", Value = "Làm mới" },
        new() { ResourceKey = "mobile.common.refresh", Locale = "en-US", Value = "Refresh" },
        new() { ResourceKey = "mobile.common.retry", Locale = "vi-VN", Value = "Thử lại" },
        new() { ResourceKey = "mobile.common.retry", Locale = "en-US", Value = "Retry" },
        new() { ResourceKey = "mobile.common.save", Locale = "vi-VN", Value = "Lưu" },
        new() { ResourceKey = "mobile.common.save", Locale = "en-US", Value = "Save" },
        new() { ResourceKey = "mobile.common.cancel", Locale = "vi-VN", Value = "Hủy" },
        new() { ResourceKey = "mobile.common.cancel", Locale = "en-US", Value = "Cancel" },
        new() { ResourceKey = "mobile.common.delete", Locale = "vi-VN", Value = "Xóa" },
        new() { ResourceKey = "mobile.common.delete", Locale = "en-US", Value = "Delete" },
        new() { ResourceKey = "mobile.common.loading", Locale = "vi-VN", Value = "Đang tải..." },
        new() { ResourceKey = "mobile.common.loading", Locale = "en-US", Value = "Loading..." },
        new() { ResourceKey = "mobile.common.empty", Locale = "vi-VN", Value = "Chưa có dữ liệu" },
        new() { ResourceKey = "mobile.common.empty", Locale = "en-US", Value = "No data available" },
        new() { ResourceKey = "mobile.common.error", Locale = "vi-VN", Value = "Đã xảy ra lỗi" },
        new() { ResourceKey = "mobile.common.error", Locale = "en-US", Value = "Something went wrong" },
        new() { ResourceKey = "mobile.common.noPermission", Locale = "vi-VN", Value = "Không có quyền truy cập" },
        new() { ResourceKey = "mobile.common.noPermission", Locale = "en-US", Value = "Access denied" },
        new() { ResourceKey = "mobile.mfa.title", Locale = "vi-VN", Value = "Bảo mật MFA" },
        new() { ResourceKey = "mobile.mfa.title", Locale = "en-US", Value = "MFA security" },
        new() { ResourceKey = "mobile.mfa.createPasskey", Locale = "vi-VN", Value = "Tạo passkey" },
        new() { ResourceKey = "mobile.mfa.createPasskey", Locale = "en-US", Value = "Create passkey" },
        new() { ResourceKey = "mobile.mfa.verify", Locale = "vi-VN", Value = "Xác minh" },
        new() { ResourceKey = "mobile.mfa.verify", Locale = "en-US", Value = "Verify" },
        new() { ResourceKey = "mobile.mfa.passkeyRegistrationFailed", Locale = "vi-VN", Value = "Đăng ký passkey thất bại" },
        new() { ResourceKey = "mobile.mfa.passkeyRegistrationFailed", Locale = "en-US", Value = "Passkey registration failed" },
        new() { ResourceKey = "mobile.mfa.setupFailed", Locale = "vi-VN", Value = "Không thể bắt đầu thiết lập MFA" },
        new() { ResourceKey = "mobile.mfa.setupFailed", Locale = "en-US", Value = "Unable to start MFA setup" },
        new() { ResourceKey = "mobile.mfa.alreadyEnabled", Locale = "vi-VN", Value = "MFA đã được bật" },
        new() { ResourceKey = "mobile.mfa.alreadyEnabled", Locale = "en-US", Value = "MFA is already enabled" },
        new() { ResourceKey = "mobile.providers.ldap", Locale = "vi-VN", Value = "LDAP/AD" },
        new() { ResourceKey = "mobile.providers.ldap", Locale = "en-US", Value = "LDAP/AD" },
        new() { ResourceKey = "mobile.providers.saml", Locale = "vi-VN", Value = "Đăng nhập SSO SAML" },
        new() { ResourceKey = "mobile.providers.saml", Locale = "en-US", Value = "SAML SSO" },

        // Operator mobile translations are seeded server-side as well as in the
        // shared frontend dictionary so a locale switch remains consistent when
        // the localization API is loaded before the app bundle.
        new() { ResourceKey = "mobile.operatorFieldOperations", Locale = "vi-VN", Value = "Vận hành hiện trường" },
        new() { ResourceKey = "mobile.operatorFieldOperations", Locale = "en-US", Value = "Field operations" },
        new() { ResourceKey = "mobile.operatorOnline", Locale = "vi-VN", Value = "Trực tuyến" },
        new() { ResourceKey = "mobile.operatorOnline", Locale = "en-US", Value = "Online" },
        new() { ResourceKey = "mobile.operatorTenant", Locale = "vi-VN", Value = "Tenant" },
        new() { ResourceKey = "mobile.operatorTenant", Locale = "en-US", Value = "Tenant" },
        new() { ResourceKey = "mobile.operatorNoTenantClaim", Locale = "vi-VN", Value = "Chưa có tenant claim" },
        new() { ResourceKey = "mobile.operatorNoTenantClaim", Locale = "en-US", Value = "No tenant claim" },
        new() { ResourceKey = "mobile.operatorIdentity", Locale = "vi-VN", Value = "Operator" },
        new() { ResourceKey = "mobile.operatorIdentity", Locale = "en-US", Value = "Operator" },
        new() { ResourceKey = "mobile.operatorProduction", Locale = "vi-VN", Value = "Sản xuất" },
        new() { ResourceKey = "mobile.operatorProduction", Locale = "en-US", Value = "Production" },
        new() { ResourceKey = "mobile.operatorTraceability", Locale = "vi-VN", Value = "Truy xuất" },
        new() { ResourceKey = "mobile.operatorTraceability", Locale = "en-US", Value = "Traceability" },
        new() { ResourceKey = "mobile.operatorQuality", Locale = "vi-VN", Value = "Chất lượng" },
        new() { ResourceKey = "mobile.operatorQuality", Locale = "en-US", Value = "Quality" },
        new() { ResourceKey = "mobile.operatorMaintenance", Locale = "vi-VN", Value = "Bảo trì" },
        new() { ResourceKey = "mobile.operatorMaintenance", Locale = "en-US", Value = "Maintenance" },
        new() { ResourceKey = "mobile.operatorSync", Locale = "vi-VN", Value = "Đồng bộ" },
        new() { ResourceKey = "mobile.operatorSync", Locale = "en-US", Value = "Sync" },
        new() { ResourceKey = "mobile.operatorAccountMenu", Locale = "vi-VN", Value = "Menu tài khoản" },
        new() { ResourceKey = "mobile.operatorAccountMenu", Locale = "en-US", Value = "Account menu" },
        new() { ResourceKey = "mobile.operatorProductionTitle", Locale = "vi-VN", Value = "Vận hành sản xuất" },
        new() { ResourceKey = "mobile.operatorProductionTitle", Locale = "en-US", Value = "Production work" },
        new() { ResourceKey = "mobile.operatorProductionDescription", Locale = "vi-VN", Value = "Ghi nhận sản lượng tại điểm làm việc. Bản ghi ngoại tuyến sẽ chờ đồng bộ." },
        new() { ResourceKey = "mobile.operatorProductionDescription", Locale = "en-US", Value = "Record output at the point of work. Offline entries remain queued until synchronised." },
        new() { ResourceKey = "mobile.operatorBatch", Locale = "vi-VN", Value = "Lô sản xuất" },
        new() { ResourceKey = "mobile.operatorBatch", Locale = "en-US", Value = "Batch" },
        new() { ResourceKey = "mobile.operatorChooseBatch", Locale = "vi-VN", Value = "Chọn lô đã bắt đầu" },
        new() { ResourceKey = "mobile.operatorChooseBatch", Locale = "en-US", Value = "Choose a started batch" },
        new() { ResourceKey = "mobile.operatorOutputQuantity", Locale = "vi-VN", Value = "Sản lượng" },
        new() { ResourceKey = "mobile.operatorOutputQuantity", Locale = "en-US", Value = "Output quantity" },
        new() { ResourceKey = "mobile.operatorRecordOperation", Locale = "vi-VN", Value = "Ghi nhận vận hành" },
        new() { ResourceKey = "mobile.operatorRecordOperation", Locale = "en-US", Value = "Record operation" },
        new() { ResourceKey = "mobile.operatorMaintenanceEyebrow", Locale = "vi-VN", Value = "BẢO DƯỠNG THIẾT BỊ" },
        new() { ResourceKey = "mobile.operatorMaintenanceEyebrow", Locale = "en-US", Value = "ASSET CARE" },
        new() { ResourceKey = "mobile.operatorMaintenanceTitle", Locale = "vi-VN", Value = "Hoàn tất bảo trì" },
        new() { ResourceKey = "mobile.operatorMaintenanceTitle", Locale = "en-US", Value = "Complete maintenance" },
        new() { ResourceKey = "mobile.operatorMaintenanceDescription", Locale = "vi-VN", Value = "Hoàn tất lệnh công việc với checklist và bằng chứng tại hiện trường, online hoặc offline." },
        new() { ResourceKey = "mobile.operatorMaintenanceDescription", Locale = "en-US", Value = "Complete assigned work orders with a checklist and field evidence, online or offline." },
        new() { ResourceKey = "mobile.operatorMachineId", Locale = "vi-VN", Value = "Mã máy" },
        new() { ResourceKey = "mobile.operatorMachineId", Locale = "en-US", Value = "Machine ID" },
        new() { ResourceKey = "mobile.operatorWorkOrderId", Locale = "vi-VN", Value = "Mã lệnh công việc" },
        new() { ResourceKey = "mobile.operatorWorkOrderId", Locale = "en-US", Value = "Work order ID" },
        new() { ResourceKey = "mobile.operatorTechnician", Locale = "vi-VN", Value = "Kỹ thuật viên" },
        new() { ResourceKey = "mobile.operatorTechnician", Locale = "en-US", Value = "Technician" },
        new() { ResourceKey = "mobile.operatorIsolationChecklist", Locale = "vi-VN", Value = "Đã hoàn tất checklist cô lập" },
        new() { ResourceKey = "mobile.operatorIsolationChecklist", Locale = "en-US", Value = "Isolation checklist complete" },
        new() { ResourceKey = "mobile.operatorCompleteWorkOrder", Locale = "vi-VN", Value = "Hoàn tất lệnh công việc" },
        new() { ResourceKey = "mobile.operatorCompleteWorkOrder", Locale = "en-US", Value = "Complete work order" },
        new() { ResourceKey = "mobile.operatorQualityEyebrow", Locale = "vi-VN", Value = "KIỂM SOÁT CHẤT LƯỢNG" },
        new() { ResourceKey = "mobile.operatorQualityEyebrow", Locale = "en-US", Value = "QUALITY CONTROL" },
        new() { ResourceKey = "mobile.operatorQualityTitle", Locale = "vi-VN", Value = "Ghi nhận kiểm tra" },
        new() { ResourceKey = "mobile.operatorQualityTitle", Locale = "en-US", Value = "Record inspection" },
        new() { ResourceKey = "mobile.operatorQualityDescription", Locale = "vi-VN", Value = "Ghi nhận kết quả theo lô. Bản ghi chờ đồng bộ vẫn hiển thị." },
        new() { ResourceKey = "mobile.operatorQualityDescription", Locale = "en-US", Value = "Capture a result against a lot. Pending records remain visible until synchronised." },
        new() { ResourceKey = "mobile.operatorLotId", Locale = "vi-VN", Value = "Mã lô" },
        new() { ResourceKey = "mobile.operatorLotId", Locale = "en-US", Value = "Lot ID" },
        new() { ResourceKey = "mobile.operatorLotPlaceholder", Locale = "vi-VN", Value = "Mã nhận diện lô" },
        new() { ResourceKey = "mobile.operatorLotPlaceholder", Locale = "en-US", Value = "Lot identifier" },
        new() { ResourceKey = "mobile.operatorInspector", Locale = "vi-VN", Value = "Người kiểm tra" },
        new() { ResourceKey = "mobile.operatorInspector", Locale = "en-US", Value = "Inspector" },
        new() { ResourceKey = "mobile.operatorInspectorPlaceholder", Locale = "vi-VN", Value = "Tên của bạn" },
        new() { ResourceKey = "mobile.operatorInspectorPlaceholder", Locale = "en-US", Value = "Your name" },
        new() { ResourceKey = "mobile.operatorMoisture", Locale = "vi-VN", Value = "Độ ẩm %" },
        new() { ResourceKey = "mobile.operatorMoisture", Locale = "en-US", Value = "Moisture %" },
        new() { ResourceKey = "mobile.operatorStatus", Locale = "vi-VN", Value = "Trạng thái" },
        new() { ResourceKey = "mobile.operatorStatus", Locale = "en-US", Value = "Status" },
        new() { ResourceKey = "mobile.operatorSaveInspection", Locale = "vi-VN", Value = "Lưu kiểm tra" },
        new() { ResourceKey = "mobile.operatorSaveInspection", Locale = "en-US", Value = "Save inspection" }
    ];
}
