import { ChangeDetectionStrategy, ChangeDetectorRef, Component, DestroyRef, OnInit, inject } from "@angular/core";
import { DatePipe, DecimalPipe } from "@angular/common";
import { FormsModule } from "@angular/forms";
import { takeUntilDestroyed } from "@angular/core/rxjs-interop";
import { HisHopePageHeaderComponent, HisHopePageLayoutComponent, HisHopeActionButtonComponent } from "@his-hope/frontend-foundation/ui";
import { HisHopeApiErrorMessageService, HisHopeI18nService, HisHopeTranslatePipe } from "@his-hope/frontend-foundation/i18n";
import { HisHopeEventReceiptDto, HisHopeFefoLotDto, HisHopeGenealogyDto, HisHopeInventoryTransactionDto, HisHopeLotReservationDto } from "@his-hope/frontend-foundation/contracts";
import { ManufacturingApiService } from "../../core/services/manufacturing-api.service";

  @Component({ standalone: true, changeDetection: ChangeDetectionStrategy.OnPush, imports: [DatePipe, DecimalPipe, FormsModule, HisHopePageHeaderComponent, HisHopePageLayoutComponent, HisHopeActionButtonComponent, HisHopeTranslatePipe], template: `
  <hh-page-layout><hh-page-header hhPageHeader [title]="'customerPortal.traceabilityTitle' | hhTranslate: 'Traceability'" [subtitle]="'customerPortal.traceabilitySubtitle' | hhTranslate: 'FEFO, reservations, genealogy and inventory events'" />
    @if (error) { <p class="error" role="alert">{{ error }}</p> }
    <section class="section"><h2>{{ 'customerPortal.fefo' | hhTranslate: 'FEFO availability' }}</h2><form class="toolbar" (ngSubmit)="loadFefo()"><input name="sku" [(ngModel)]="sku" [placeholder]="'customerPortal.productSku' | hhTranslate: 'Product SKU'" required /><hh-action-button kind="primary" icon="sort" type="submit" [label]="'common.search' | hhTranslate: 'Search'" [disabled]="busy" /></form>@if (!fefo.length) { <p class="empty">{{ 'customerPortal.noFefoLots' | hhTranslate: 'No FEFO lots.' }}</p> } @else { <div class="grid">@for (lot of fefo; track lot.lotId) { <article class="card"><strong>{{ lot.sku }}</strong><span>{{ lot.availableQuantity | number:'1.0-3' }} / {{ lot.quantity | number:'1.0-3' }} {{ lot.uom }}</span><small>{{ lot.bestBefore ? (lot.bestBefore | date:'mediumDate') : ('customerPortal.noExpiry' | hhTranslate:'No expiry') }}</small><hh-action-button kind="row" icon="account_tree" [label]="'customerPortal.openGenealogy' | hhTranslate: 'Genealogy'" (pressed)="loadGenealogy(lot.lotId)" /></article> }</div> }</section>
    <section class="section"><h2>{{ 'customerPortal.reservationRelease' | hhTranslate: 'Release reservation' }}</h2><form class="toolbar" (ngSubmit)="release()"><input name="reservationId" [(ngModel)]="reservationId" [placeholder]="'customerPortal.reservationId' | hhTranslate: 'Reservation ID'" required /><hh-action-button kind="secondary" icon="lock_open" type="submit" [label]="'customerPortal.release' | hhTranslate: 'Release'" [disabled]="busy" /></form></section>
    <section class="section"><h2>{{ 'customerPortal.inventoryTransactions' | hhTranslate: 'Inventory transactions' }}</h2><form class="toolbar" (ngSubmit)="loadTransactions()"><input name="lotId" [(ngModel)]="lotId" [placeholder]="'customerPortal.lotId' | hhTranslate: 'Lot ID'" required /><hh-action-button kind="secondary" icon="history" type="submit" [label]="'common.load' | hhTranslate: 'Load'" [disabled]="busy" /></form>@if (transactions.length) { <div class="rows">@for (tx of transactions; track tx.id) { <div class="row"><strong>{{ tx.transactionType }}</strong><span>{{ tx.quantity | number:'1.0-3' }} {{ tx.uom }}</span><small>{{ tx.facilityId }} · {{ tx.occurredAt | date:'medium' }}</small></div> }</div> }</section>
    <section class="section"><h2>{{ 'customerPortal.reservations' | hhTranslate: 'Reservations' }}</h2><form class="toolbar" (ngSubmit)="loadReservations()"><input name="reservationLotId" [(ngModel)]="lotId" [placeholder]="'customerPortal.lotId' | hhTranslate: 'Lot ID'" required /><select name="reservationStatus" [(ngModel)]="reservationStatus"><option value="">{{ 'customerPortal.allStatuses' | hhTranslate: 'All statuses' }}</option><option value="Reserved">{{ 'customerPortal.reserved' | hhTranslate: 'Reserved' }}</option><option value="Released">{{ 'customerPortal.released' | hhTranslate: 'Released' }}</option></select><hh-action-button kind="secondary" icon="list_alt" type="submit" [label]="'common.load' | hhTranslate: 'Load'" [disabled]="busy" /></form><form class="toolbar" (ngSubmit)="reserve()"><input name="reservationReferenceType" [(ngModel)]="referenceType" [placeholder]="'customerPortal.referenceType' | hhTranslate: 'Reference type'" required /><input name="reservationReferenceId" [(ngModel)]="referenceId" [placeholder]="'customerPortal.referenceId' | hhTranslate: 'Reference ID'" required /><input name="reservationQuantity" type="number" min="0.001" step="0.001" [(ngModel)]="reservationQuantity" [placeholder]="'customerPortal.quantity' | hhTranslate: 'Quantity'" required /><hh-action-button kind="primary" icon="lock" type="submit" [label]="'customerPortal.reserve' | hhTranslate: 'Reserve'" [disabled]="busy" /></form>@if (!reservations.length) { <p class="empty">{{ 'customerPortal.noReservations' | hhTranslate: 'No reservations.' }}</p> } @else { <div class="rows">@for (reservation of reservations; track reservation.id) { <div class="row"><strong>{{ reservation.referenceType }}</strong><span>{{ reservation.quantity | number:'1.0-3' }} {{ reservation.uom }} · {{ reservation.status }}</span><small>{{ reservation.id }} · {{ reservation.createdAt | date:'medium' }}</small>@if (reservation.status === 'Reserved') { <hh-action-button kind="row" icon="lock_open" [label]="'customerPortal.release' | hhTranslate: 'Release'" [disabled]="busy" (pressed)="releaseReservation(reservation)" /> }</div> }</div> }</section>
    <section class="section"><h2>{{ 'customerPortal.eventReceipts' | hhTranslate: 'Event receipts' }}</h2><hh-action-button kind="secondary" icon="sync" [label]="'common.refresh' | hhTranslate: 'Refresh'" (pressed)="loadEvents()" />@if (!events.length) { <p class="empty">{{ 'customerPortal.noEventReceipts' | hhTranslate: 'No event receipts.' }}</p> } @else { <div class="rows">@for (event of events; track event.id) { <div class="row"><strong>{{ event.eventType }}</strong><span>{{ event.aggregateId }}</span><small>{{ event.receivedAt | date:'medium' }}</small></div> }</div> }</section>
    @if (genealogy) { <section class="section"><h2>{{ 'customerPortal.genealogy' | hhTranslate: 'Genealogy' }}</h2><p><strong>{{ genealogy.lot.sku }}</strong> · {{ genealogy.lot.id }}</p><div class="rows">@for (relation of genealogy.relations; track relation.transformationId + relation.lotId) { <div class="row"><strong>{{ relation.role }}</strong><span>{{ relation.sku }} · {{ relation.quantity | number:'1.0-3' }}</span><small>{{ relation.transformationId }}</small></div> }</div></section> }
  </hh-page-layout>
`, styles: [`:host{display:block}.section{margin-bottom:var(--space-xl)}.toolbar{display:flex;gap:var(--space-sm);align-items:center;flex-wrap:wrap;margin:var(--space-md) 0}.toolbar input{min-height:var(--control-height);min-width:260px;padding:0 var(--space-sm);border:1px solid var(--border-subtle);border-radius:var(--radius-control);background:var(--surface-raised);color:var(--text-primary);font:inherit}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:var(--space-md)}.card,.row{display:grid;gap:var(--space-xs);padding:var(--space-md);border:1px solid var(--border-subtle);border-radius:var(--radius-card)}.rows{display:grid;gap:var(--space-sm)}small,.empty{color:var(--text-secondary)}.error{color:var(--color-danger)}`] })
export class TraceabilityPageComponent implements OnInit {
  private readonly api = inject(ManufacturingApiService); private readonly errors = inject(HisHopeApiErrorMessageService); private readonly cdr = inject(ChangeDetectorRef); private readonly destroyRef = inject(DestroyRef); readonly i18n = inject(HisHopeI18nService);
  sku = ""; lotId = ""; reservationId = ""; reservationStatus = ""; referenceType = "ProductionOrder"; referenceId = ""; reservationQuantity = 0; busy = false; error = ""; fefo: HisHopeFefoLotDto[] = []; transactions: HisHopeInventoryTransactionDto[] = []; reservations: HisHopeLotReservationDto[] = []; events: HisHopeEventReceiptDto[] = []; genealogy: HisHopeGenealogyDto | null = null;
  ngOnInit(): void { this.loadEvents(); }
  loadFefo(): void { if (!this.sku.trim()) return; this.busy = true; this.api.getFefoLots(this.sku.trim()).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: (items) => { this.fefo = items ?? []; this.busy = false; this.cdr.markForCheck(); }, error: (e) => this.fail(e) }); }
  loadGenealogy(id: string): void { this.lotId = id; this.api.getLotGenealogy(id).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: (item) => { this.genealogy = item; this.cdr.markForCheck(); }, error: (e) => this.fail(e) }); }
  loadTransactions(): void { if (!this.lotId.trim()) return; this.api.getInventoryTransactions(this.lotId.trim()).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: (items) => { this.transactions = items ?? []; this.cdr.markForCheck(); }, error: (e) => this.fail(e) }); }
  loadReservations(): void { if (!this.lotId.trim()) return; this.busy = true; this.api.getLotReservations(this.lotId.trim(), this.reservationStatus || undefined).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: (items) => { this.reservations = items ?? []; this.busy = false; this.cdr.markForCheck(); }, error: (e) => this.fail(e) }); }
  reserve(): void { if (!this.lotId.trim() || !this.referenceType.trim() || !this.referenceId.trim() || this.reservationQuantity <= 0) { this.error = this.i18n.t("customerPortal.reservationFormInvalid", "Lot, reference and a positive quantity are required."); return; } this.busy = true; this.api.reserveLot(this.lotId.trim(), { referenceType: this.referenceType.trim(), referenceId: this.referenceId.trim(), quantity: this.reservationQuantity }).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: (reservation) => { this.reservations = [reservation, ...this.reservations.filter((item) => item.id !== reservation.id)]; this.busy = false; this.cdr.markForCheck(); }, error: (e) => this.fail(e) }); }
  loadEvents(): void { this.api.getEventReceipts().pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: (items) => { this.events = items ?? []; this.cdr.markForCheck(); }, error: (e) => this.fail(e) }); }
  release(): void { if (!this.reservationId.trim()) return; this.busy = true; this.api.releaseReservation(this.reservationId.trim()).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: () => { this.reservationId = ""; this.busy = false; this.cdr.markForCheck(); }, error: (e) => this.fail(e) }); }
  releaseReservation(reservation: HisHopeLotReservationDto): void { this.busy = true; this.api.releaseReservation(reservation.id).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: (updated) => { this.reservations = this.reservations.map((item) => item.id === updated.id ? updated : item); this.busy = false; this.cdr.markForCheck(); }, error: (e) => this.fail(e) }); }
  private fail(error: unknown): void { this.error = this.errors.message(error, "customerPortal.traceabilityLoadFailed"); this.busy = false; this.cdr.markForCheck(); }
}
