import { AfterViewInit, ChangeDetectionStrategy, ChangeDetectorRef, Component, DestroyRef, OnInit, inject } from "@angular/core";
import { DecimalPipe } from "@angular/common";
import { FormsModule } from "@angular/forms";
import { takeUntilDestroyed } from "@angular/core/rxjs-interop";
import { HisHopePageHeaderComponent, HisHopePageLayoutComponent, HisHopeStateComponent, HisHopeActionButtonComponent, HisHopeTabsComponent , HisHopeSelectComponent} from "@his-hope/frontend-foundation/ui";
import { HisHopeApiErrorMessageService, HisHopeI18nService, HisHopeTranslatePipe } from "@his-hope/frontend-foundation/i18n";
import { HisHopeProductDto, HisHopeUomDto, HisHopeUomConversionDto, HisHopeFacilityDto, HisHopeWarehouseDto, HisHopeStorageLocationDto } from "@his-hope/frontend-foundation/contracts";
import { ManufacturingApiService } from "../../core/services/manufacturing-api.service";
import { TenantContextService } from "../../core/services/tenant-context.service";

@Component({
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [DecimalPipe, FormsModule, HisHopePageHeaderComponent, HisHopePageLayoutComponent, HisHopeStateComponent, HisHopeActionButtonComponent, HisHopeTabsComponent, HisHopeTranslatePipe, HisHopeSelectComponent],
  template: `
    <hh-page-layout><hh-page-header hhPageHeader [title]="'customerPortal.masterDataTitle' | hhTranslate: 'Master data'" [subtitle]="subtitle" /><hh-tabs label="Master data sections"><button role="tab" type="button" [attr.aria-selected]="activeTab === 'products'" [class.active]="activeTab === 'products'" (click)="selectTab('products')">{{ 'customerPortal.products' | hhTranslate: 'Products' }}</button><button role="tab" type="button" [attr.aria-selected]="activeTab === 'locations'" [class.active]="activeTab === 'locations'" (click)="selectTab('locations')">{{ 'customerPortal.locations' | hhTranslate: 'Facilities and storage locations' }}</button><button role="tab" type="button" [attr.aria-selected]="activeTab === 'uoms'" [class.active]="activeTab === 'uoms'" (click)="selectTab('uoms')">{{ 'customerPortal.uoms' | hhTranslate: 'Units of measure' }}</button></hh-tabs>
      @if (loading) { <hh-state kind="loading" [message]="'customerPortal.loadingMasterData' | hhTranslate: 'Loading master data…'" /> }
      @else if (error) { <hh-state kind="error" [message]="error" /> }
      @else {
        <section class="section"><div class="heading"><h2>{{ 'customerPortal.products' | hhTranslate: 'Products' }}</h2><hh-action-button kind="secondary" icon="add_box" [label]="'customerPortal.addProduct' | hhTranslate: 'Add product'" (pressed)="productDraft = { sku: '', name: '', baseUomCode: uoms[0]?.code ?? '', active: true }" /></div>
          @if (productDraft) { <form class="form" (ngSubmit)="saveProduct()"><label>{{ 'customerPortal.materialSku' | hhTranslate: 'SKU' }}<input name="sku" [(ngModel)]="productDraft.sku" [disabled]="!!productDraft.id" required /></label><label>{{ 'common.name' | hhTranslate: 'Name' }}<input name="name" [(ngModel)]="productDraft.name" required /></label><label for="productUom">{{ 'customerPortal.baseUom' | hhTranslate: 'Base UOM' }}<hh-select id="productUom" name="productUom" [(ngModel)]="productDraft.baseUomCode" required>@for (uom of uoms; track uom.code) { <option [value]="uom.code">{{ uom.code }} · {{ uom.name }}</option> }</hh-select></label><label><input name="productActive" type="checkbox" [(ngModel)]="productDraft.active" /> {{ 'common.active' | hhTranslate: 'Active' }}</label><hh-action-button kind="primary" icon="save" type="submit" [label]="'common.save' | hhTranslate: 'Save'" [disabled]="busy" /></form> }
          @if (!products.length) { <p class="empty">{{ 'customerPortal.noProducts' | hhTranslate: 'No products.' }}</p> } @else { <div class="grid">@for (product of products; track product.id) { <article class="card"><strong>{{ product.sku }}</strong><span>{{ product.name }}</span><small>{{ product.baseUomCode }} · {{ product.active ? ('common.active' | hhTranslate:'Active') : ('common.inactive' | hhTranslate:'Inactive') }}</small><hh-action-button kind="row" mode="icon-only" icon="edit" [label]="'common.edit' | hhTranslate: 'Edit'" (pressed)="editProduct(product)" /></article> }</div> }
        </section>
        <section class="section"><div class="heading"><h2>{{ 'customerPortal.locations' | hhTranslate: 'Facilities and storage locations' }}</h2><div class="actions"><hh-action-button kind="secondary" icon="add_home_work" [label]="'customerPortal.addFacility' | hhTranslate: 'Add facility'" (pressed)="startFacility()" /><hh-action-button kind="secondary" icon="warehouse" [label]="'customerPortal.addWarehouse' | hhTranslate: 'Add warehouse'" (pressed)="startWarehouse()" /><hh-action-button kind="secondary" icon="shelves" [label]="'customerPortal.addStorageLocation' | hhTranslate: 'Add storage location'" (pressed)="startStorageLocation()" /></div></div>
          @if (facilityDraft) { <form class="form" (ngSubmit)="saveFacility()"><label>{{ 'customerPortal.facilityCode' | hhTranslate: 'Facility code' }}<input name="facilityCode" [(ngModel)]="facilityDraft.code" [disabled]="!!facilityDraft.id" required /></label><label>{{ 'customerPortal.facilityName' | hhTranslate: 'Facility name' }}<input name="facilityName" [(ngModel)]="facilityDraft.name" required /></label><label><input name="facilityActive" type="checkbox" [(ngModel)]="facilityDraft.active" /> {{ 'common.active' | hhTranslate: 'Active' }}</label><hh-action-button kind="primary" icon="save" type="submit" [label]="'common.save' | hhTranslate: 'Save'" [disabled]="busy" /></form> }
          @if (warehouseDraft) { <form class="form" (ngSubmit)="saveWarehouse()"><label for="warehouseFacility">{{ 'customerPortal.facility' | hhTranslate: 'Facility' }}<hh-select id="warehouseFacility" name="warehouseFacility" [(ngModel)]="warehouseDraft.facilityId" required><option value="">{{ 'customerPortal.selectFacility' | hhTranslate: 'Select facility' }}</option>@for (facility of facilities; track facility.id) { <option [value]="facility.id">{{ facility.code }} · {{ facility.name }}</option> }</hh-select></label><label>{{ 'customerPortal.warehouseCode' | hhTranslate: 'Warehouse code' }}<input name="warehouseCode" [(ngModel)]="warehouseDraft.code" [disabled]="!!warehouseDraft.id" required /></label><label>{{ 'customerPortal.warehouseName' | hhTranslate: 'Warehouse name' }}<input name="warehouseName" [(ngModel)]="warehouseDraft.name" required /></label><label><input name="warehouseActive" type="checkbox" [(ngModel)]="warehouseDraft.active" /> {{ 'common.active' | hhTranslate: 'Active' }}</label><hh-action-button kind="primary" icon="save" type="submit" [label]="'common.save' | hhTranslate: 'Save'" [disabled]="busy" /></form> }
          @if (storageLocationDraft) { <form class="form" (ngSubmit)="saveStorageLocation()"><label for="locationWarehouse">{{ 'customerPortal.warehouse' | hhTranslate: 'Warehouse' }}<hh-select id="locationWarehouse" name="locationWarehouse" [(ngModel)]="storageLocationDraft.warehouseId" required><option value="">{{ 'customerPortal.selectWarehouse' | hhTranslate: 'Select warehouse' }}</option>@for (warehouse of warehouses; track warehouse.id) { <option [value]="warehouse.id">{{ warehouse.code }} · {{ warehouse.name }}</option> }</hh-select></label><label>{{ 'customerPortal.storageLocationCode' | hhTranslate: 'Location code' }}<input name="locationCode" [(ngModel)]="storageLocationDraft.code" [disabled]="!!storageLocationDraft.id" required /></label><label>{{ 'customerPortal.storageLocationName' | hhTranslate: 'Location name' }}<input name="locationName" [(ngModel)]="storageLocationDraft.name" required /></label><label><input name="locationActive" type="checkbox" [(ngModel)]="storageLocationDraft.active" /> {{ 'common.active' | hhTranslate: 'Active' }}</label><hh-action-button kind="primary" icon="save" type="submit" [label]="'common.save' | hhTranslate: 'Save'" [disabled]="busy" /></form> }
          <div class="grid"><article class="card"><strong>{{ 'customerPortal.facilities' | hhTranslate: 'Facilities' }}</strong>@for (facility of facilities; track facility.id) { <span>{{ facility.code }} · {{ facility.name }} <hh-action-button kind="row" mode="icon-only" icon="edit" [label]="'common.edit' | hhTranslate: 'Edit'" (pressed)="editFacility(facility)" /></span> } @empty { <small>{{ 'customerPortal.noFacilities' | hhTranslate: 'No facilities.' }}</small> }</article><article class="card"><strong>{{ 'customerPortal.warehouses' | hhTranslate: 'Warehouses' }}</strong>@for (warehouse of warehouses; track warehouse.id) { <span>{{ warehouse.code }} · {{ warehouse.name }} <small>({{ facilityName(warehouse.facilityId) }})</small> <hh-action-button kind="row" mode="icon-only" icon="edit" [label]="'common.edit' | hhTranslate: 'Edit'" (pressed)="editWarehouse(warehouse)" /></span> } @empty { <small>{{ 'customerPortal.noWarehouses' | hhTranslate: 'No warehouses.' }}</small> }</article><article class="card"><strong>{{ 'customerPortal.storageLocations' | hhTranslate: 'Storage locations' }}</strong>@for (location of storageLocations; track location.id) { <span>{{ location.code }} · {{ location.name }} <small>({{ warehouseName(location.warehouseId) }})</small> <hh-action-button kind="row" mode="icon-only" icon="edit" [label]="'common.edit' | hhTranslate: 'Edit'" (pressed)="editStorageLocation(location)" /></span> } @empty { <small>{{ 'customerPortal.noStorageLocations' | hhTranslate: 'No storage locations.' }}</small> }</article></div>
        </section>
        <section class="section"><div class="heading"><h2>{{ 'customerPortal.uoms' | hhTranslate: 'Units of measure' }}</h2><div class="actions"><hh-action-button kind="secondary" icon="straighten" [label]="'customerPortal.addUom' | hhTranslate: 'Add UOM'" (pressed)="startUom()" /><hh-action-button kind="secondary" icon="swap_horiz" [label]="'customerPortal.addConversion' | hhTranslate: 'Add conversion'" (pressed)="startConversion()" /></div></div>
          @if (uomDraft) { <form class="form" (ngSubmit)="saveUom()"><label>{{ 'customerPortal.uomCode' | hhTranslate: 'UOM code' }}<input name="uomCode" [(ngModel)]="uomDraft.code" [disabled]="!!uomDraft.id" required /></label><label>{{ 'customerPortal.uomName' | hhTranslate: 'UOM name' }}<input name="uomName" [(ngModel)]="uomDraft.name" required /></label><label>{{ 'customerPortal.uomDimension' | hhTranslate: 'Dimension' }}<input name="uomDimension" [(ngModel)]="uomDraft.dimension" required /></label><label><input name="uomActive" type="checkbox" [(ngModel)]="uomDraft.active" /> {{ 'common.active' | hhTranslate: 'Active' }}</label><hh-action-button kind="primary" icon="save" type="submit" [label]="'common.save' | hhTranslate: 'Save'" [disabled]="busy" /></form> }
          @if (!uoms.length) { <p class="empty">{{ 'customerPortal.noUoms' | hhTranslate: 'No units of measure.' }}</p> } @else { <div class="grid">@for (uom of uoms; track uom.code) { <article class="card"><strong>{{ uom.code }}</strong><span>{{ uom.name }}</span><small>{{ uom.dimension }} · {{ uom.active ? ('common.active' | hhTranslate:'Active') : ('common.inactive' | hhTranslate:'Inactive') }}</small><hh-action-button kind="row" mode="icon-only" icon="edit" [label]="'common.edit' | hhTranslate: 'Edit'" (pressed)="editUom(uom)" /></article> }</div> }
          @if (conversionDraft) { <form class="form" (ngSubmit)="saveConversion()"><label for="from">{{ 'customerPortal.fromUom' | hhTranslate: 'From' }}<hh-select id="from" name="from" [(ngModel)]="conversionDraft.fromCode">@for (uom of uoms; track uom.code) { <option [value]="uom.code">{{ uom.code }} · {{ uom.name }}</option> }</hh-select></label><label for="to">{{ 'customerPortal.toUom' | hhTranslate: 'To' }}<hh-select id="to" name="to" [(ngModel)]="conversionDraft.toCode">@for (uom of uoms; track uom.code) { <option [value]="uom.code">{{ uom.code }} · {{ uom.name }}</option> }</hh-select></label><label>{{ 'customerPortal.factor' | hhTranslate: 'Factor' }}<input name="factor" type="number" min="0.000001" step="0.000001" [(ngModel)]="conversionDraft.factor" required /></label><label><input name="conversionActive" type="checkbox" [(ngModel)]="conversionDraft.active" /> {{ 'common.active' | hhTranslate: 'Active' }}</label><hh-action-button kind="primary" icon="save" type="submit" [label]="'common.save' | hhTranslate: 'Save'" [disabled]="busy" /></form> }
          @if (!conversions.length) { <p class="empty">{{ 'customerPortal.noConversions' | hhTranslate: 'No conversions.' }}</p> } @else { <div class="grid">@for (conversion of conversions; track conversion.id) { <article class="card"><strong>{{ conversion.fromCode }} → {{ conversion.toCode }}</strong><span>{{ conversion.factor | number:'1.0-6' }}</span><small>{{ conversion.active ? ('common.active' | hhTranslate:'Active') : ('common.inactive' | hhTranslate:'Inactive') }}</small><hh-action-button kind="row" mode="icon-only" icon="edit" [label]="'common.edit' | hhTranslate: 'Edit'" (pressed)="editConversion(conversion)" /></article> }</div> }
        </section>
      }
    </hh-page-layout>
  `,
  styles: [`:host{display:block}.section{margin-bottom:var(--space-xl)}.heading{display:flex;justify-content:space-between;align-items:center;gap:var(--space-md)}.actions{display:flex;flex-wrap:wrap;gap:var(--space-sm)}.form{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:var(--space-md);padding:var(--space-md);margin:var(--space-md) 0;border:1px solid var(--border-subtle);border-radius:var(--radius-card);background:var(--surface-muted)}label{display:grid;gap:var(--space-2xs);font-size:var(--font-size-caption);color:var(--text-secondary)}input:not([type="checkbox"]),select{min-height:var(--control-height);padding:0 var(--space-sm);border:1px solid var(--border-subtle);border-radius:var(--radius-control);background:var(--surface-raised);color:var(--text-primary);font:inherit}input[type="checkbox"]{inline-size:1.125rem;block-size:1.125rem;min-height:0;margin:0 var(--space-xs) 0 0;padding:0;border:1px solid var(--border-default);border-radius:var(--radius-input);accent-color:var(--color-primary);vertical-align:middle}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:var(--space-md)}.card{display:grid;gap:var(--space-xs);padding:var(--space-md);border:1px solid var(--border-subtle);border-radius:var(--radius-card)}.card > span{display:flex;align-items:center;gap:var(--space-xs);min-width:0}.card small,.empty{color:var(--text-secondary)}`],
})
export class MasterDataPageComponent implements OnInit, AfterViewInit {
  activeTab = "products";
  selectTab(tab: string): void { this.activeTab = tab; this.applyTabVisibility(); this.cdr.markForCheck(); }
  ngAfterViewInit(): void { const observer = new MutationObserver(() => { if (document.querySelectorAll("section.section").length) { this.applyTabVisibility(); observer.disconnect(); } }); observer.observe(document.body, { childList: true, subtree: true }); this.applyTabVisibility(); }
  private applyTabVisibility(): void { const sections = Array.from(document.querySelectorAll<HTMLElement>("section.section")); const index = this.activeTab === "products" ? 0 : this.activeTab === "locations" ? 1 : 2; sections.forEach((section, i) => section.hidden = i !== index); }
  private readonly api = inject(ManufacturingApiService); private readonly tenant = inject(TenantContextService); private readonly errors = inject(HisHopeApiErrorMessageService); private readonly cdr = inject(ChangeDetectorRef); private readonly destroyRef = inject(DestroyRef); readonly i18n = inject(HisHopeI18nService);
  loading = true; error = ""; busy = false; tenantLabel: string | null = null; products: HisHopeProductDto[] = []; uoms: HisHopeUomDto[] = []; conversions: HisHopeUomConversionDto[] = [];
  productDraft: { id?: string; sku: string; name: string; baseUomCode: string; active: boolean } | null = null; uomDraft: { id?: string; code: string; name: string; dimension: string; active: boolean } | null = null; conversionDraft: { id?: string; fromCode: string; toCode: string; factor: number; active: boolean } | null = null;
  facilities: HisHopeFacilityDto[] = []; warehouses: HisHopeWarehouseDto[] = []; storageLocations: HisHopeStorageLocationDto[] = [];
  facilityDraft: { id?: string; code: string; name: string; active: boolean } | null = null; warehouseDraft: { id?: string; facilityId: string; code: string; name: string; active: boolean } | null = null; storageLocationDraft: { id?: string; warehouseId: string; code: string; name: string; active: boolean } | null = null;
  get subtitle(): string { return this.i18n.t("customerPortal.tenantScope", "Tenant: {{tenant}}", { tenant: this.tenantLabel ?? "—" }); }
  ngOnInit(): void { this.tenant.activeTenantLabel$.pipe(takeUntilDestroyed(this.destroyRef)).subscribe((label) => { this.tenantLabel = label; this.cdr.markForCheck(); }); this.tenant.activeTenantKey$.pipe(takeUntilDestroyed(this.destroyRef)).subscribe(() => this.load()); }
  load(): void { this.loading = true; this.api.getProducts().pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: (products) => { this.products = products ?? []; this.api.getUoms().pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: (uoms) => { this.uoms = uoms ?? []; this.api.getUomConversions().pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: (items) => { this.conversions = items ?? []; this.loadLocations(); }, error: (e) => this.fail(e) }); }, error: (e) => this.fail(e) }); }, error: (e) => this.fail(e) }); }
  private loadLocations(): void { this.api.getFacilities().pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: (facilities) => { this.facilities = facilities ?? []; this.api.getWarehouses().pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: (warehouses) => { this.warehouses = warehouses ?? []; this.api.getStorageLocations().pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: (locations) => { this.storageLocations = locations ?? []; this.loading = false; this.cdr.markForCheck(); }, error: (e) => this.fail(e) }); }, error: (e) => this.fail(e) }); }, error: (e) => this.fail(e) }); }
  editProduct(product: HisHopeProductDto): void { this.productDraft = { id: product.id, sku: product.sku, name: product.name, baseUomCode: product.baseUomCode, active: product.active }; }
  startFacility(): void { this.facilityDraft = { code: "", name: "", active: true }; }
  editFacility(facility: HisHopeFacilityDto): void { this.facilityDraft = { id: facility.id, code: facility.code, name: facility.name, active: facility.active }; }
  startWarehouse(): void { this.warehouseDraft = { facilityId: this.facilities[0]?.id ?? "", code: "", name: "", active: true }; }
  editWarehouse(warehouse: HisHopeWarehouseDto): void { this.warehouseDraft = { id: warehouse.id, facilityId: warehouse.facilityId, code: warehouse.code, name: warehouse.name, active: warehouse.active }; }
  startStorageLocation(): void { this.storageLocationDraft = { warehouseId: this.warehouses[0]?.id ?? "", code: "", name: "", active: true }; }
  editStorageLocation(location: HisHopeStorageLocationDto): void { this.storageLocationDraft = { id: location.id, warehouseId: location.warehouseId, code: location.code, name: location.name, active: location.active }; }
   saveFacility(): void { const key = this.tenant.getActiveTenantKey(); const draft = this.facilityDraft; if (!key || !draft?.code.trim() || !draft.name.trim()) { this.error = this.i18n.t("customerPortal.masterDataFormInvalid", "Required fields are missing."); return; } this.busy = true; const request = draft.id ? this.api.updateFacility(draft.id, { code: draft.code.trim(), name: draft.name.trim(), active: draft.active }) : this.api.createFacility({ code: draft.code.trim(), name: draft.name.trim(), active: draft.active }); request.pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: () => { this.facilityDraft = null; this.busy = false; this.load(); }, error: (e) => { this.error = this.errors.message(e, "customerPortal.masterDataSaveFailed"); this.busy = false; this.cdr.markForCheck(); } }); }
   saveWarehouse(): void { const key = this.tenant.getActiveTenantKey(); const draft = this.warehouseDraft; if (!key || !draft?.facilityId || !draft.code.trim() || !draft.name.trim()) { this.error = this.i18n.t("customerPortal.masterDataFormInvalid", "Required fields are missing."); return; } this.busy = true; const request = draft.id ? this.api.updateWarehouse(draft.id, { facilityId: draft.facilityId, code: draft.code.trim(), name: draft.name.trim(), active: draft.active }) : this.api.createWarehouse({ facilityId: draft.facilityId, code: draft.code.trim(), name: draft.name.trim(), active: draft.active }); request.pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: () => { this.warehouseDraft = null; this.busy = false; this.load(); }, error: (e) => { this.error = this.errors.message(e, "customerPortal.masterDataSaveFailed"); this.busy = false; this.cdr.markForCheck(); } }); }
   saveStorageLocation(): void { const key = this.tenant.getActiveTenantKey(); const draft = this.storageLocationDraft; if (!key || !draft?.warehouseId || !draft.code.trim() || !draft.name.trim()) { this.error = this.i18n.t("customerPortal.masterDataFormInvalid", "Required fields are missing."); return; } this.busy = true; const request = draft.id ? this.api.updateStorageLocation(draft.id, { warehouseId: draft.warehouseId, code: draft.code.trim(), name: draft.name.trim(), active: draft.active }) : this.api.createStorageLocation({ warehouseId: draft.warehouseId, code: draft.code.trim(), name: draft.name.trim(), active: draft.active }); request.pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: () => { this.storageLocationDraft = null; this.busy = false; this.load(); }, error: (e) => { this.error = this.errors.message(e, "customerPortal.masterDataSaveFailed"); this.busy = false; this.cdr.markForCheck(); } }); }
  facilityName(id: string): string { return this.facilities.find((item) => item.id === id)?.name ?? id; }
  warehouseName(id: string): string { return this.warehouses.find((item) => item.id === id)?.name ?? id; }
  startUom(): void { this.error = ""; this.uomDraft = { code: "", name: "", dimension: "mass", active: true }; }
  editUom(uom: HisHopeUomDto): void { this.uomDraft = { id: uom.id, code: uom.code, name: uom.name, dimension: uom.dimension, active: uom.active }; }
  saveUom(): void { const draft = this.uomDraft; if (!draft?.code.trim() || !draft.name.trim() || !draft.dimension.trim()) { this.error = this.i18n.t("customerPortal.masterDataFormInvalid", "Required fields are missing."); return; } this.busy = true; const request = draft.id ? this.api.updateUom(draft.id, { code: draft.code.trim(), name: draft.name.trim(), dimension: draft.dimension.trim(), active: draft.active }) : this.api.createUom({ code: draft.code.trim(), name: draft.name.trim(), dimension: draft.dimension.trim(), active: draft.active }); request.pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: () => { this.uomDraft = null; this.busy = false; this.load(); }, error: (e) => { this.error = this.errors.message(e, "customerPortal.masterDataSaveFailed"); this.busy = false; this.cdr.markForCheck(); } }); }
  startConversion(): void { this.conversionDraft = { fromCode: this.uoms[0]?.code ?? "", toCode: this.uoms[1]?.code ?? this.uoms[0]?.code ?? "", factor: 1, active: true }; }
   saveProduct(): void { const key = this.tenant.getActiveTenantKey(); const draft = this.productDraft; if (!key || !draft?.sku.trim() || !draft.name.trim() || !draft.baseUomCode) { this.error = this.i18n.t("customerPortal.masterDataFormInvalid", "Required fields are missing."); return; } this.busy = true; const request = draft.id ? this.api.updateProduct(draft.id, { name: draft.name.trim(), baseUomCode: draft.baseUomCode, active: draft.active }) : this.api.createProduct({ sku: draft.sku.trim(), name: draft.name.trim(), baseUomCode: draft.baseUomCode, active: draft.active }); request.pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: () => { this.productDraft = null; this.busy = false; this.load(); }, error: (e) => { this.error = this.errors.message(e, "customerPortal.masterDataSaveFailed"); this.busy = false; this.cdr.markForCheck(); } }); }
  editConversion(conversion: HisHopeUomConversionDto): void { this.conversionDraft = { id: conversion.id, fromCode: conversion.fromCode, toCode: conversion.toCode, factor: conversion.factor, active: conversion.active }; }
  saveConversion(): void { const draft = this.conversionDraft; if (!draft?.fromCode || !draft.toCode || draft.factor <= 0) { this.error = this.i18n.t("customerPortal.masterDataFormInvalid", "Required fields are missing."); return; } this.busy = true; const request = draft.id ? this.api.updateUomConversion(draft.id, { fromCode: draft.fromCode, toCode: draft.toCode, factor: draft.factor, active: draft.active }) : this.api.createUomConversion(draft); request.pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: () => { this.conversionDraft = null; this.busy = false; this.load(); }, error: (e) => { this.error = this.errors.message(e, "customerPortal.masterDataSaveFailed"); this.busy = false; this.cdr.markForCheck(); } }); }
  private fail(error: unknown): void { this.error = this.errors.message(error, "customerPortal.masterDataLoadFailed"); this.loading = false; this.cdr.markForCheck(); }
}
