apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: his-hope-system
namePrefix: his-hope-

commonLabels:
  app.kubernetes.io/part-of: his-hope
  app.kubernetes.io/managed-by: kustomize
  his-hope.io/security-boundary: node-system

resources:
  - ../../base/seccomp-profiles.yaml
  - ../../base/seccomp-daemonset.yaml
