apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nuget-cache-pvc
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/part-of: his-hope-ci
    app.kubernetes.io/component: cache
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
