// <auto-generated />
using System;
using His.Hope.AgentHarness.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace His.Hope.AgentHarness.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HarnessDbContext))]
    partial class HarnessDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("harness")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("His.Hope.AgentHarness.Core.Models.AgentPoolState", b =>
                {
                    b.Property<string>("AgentName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("agent_name");

                    b.Property<int>("AvailableSlots")
                        .HasColumnType("integer")
                        .HasColumnName("available_slots");

                    b.Property<string>("CircuitState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("circuit_state");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<DateTime>("LastHeartbeat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat");

                    b.Property<int>("TotalSlots")
                        .HasColumnType("integer")
                        .HasColumnName("total_slots");

                    b.HasKey("AgentName");

                    b.ToTable("agent_pool", "harness");
                });

            modelBuilder.Entity("His.Hope.AgentHarness.Core.Models.AgentRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("agent_name");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<string>("CircuitState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("circuit_state");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("confidence_score");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("integer")
                        .HasColumnName("max_retries");

                    b.Property<string>("OutputArtifactRef")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("output_artifact_ref");

                    b.Property<Guid>("PipelineRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("pipeline_run_id");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("task_description");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("timeout_seconds");

                    b.HasKey("Id");

                    b.HasIndex("AgentName")
                        .HasDatabaseName("ix_agent_runs_agent_name");

                    b.HasIndex("PipelineRunId")
                        .HasDatabaseName("ix_agent_runs_pipeline_run_id");

                    b.ToTable("agent_runs", "harness");
                });

            modelBuilder.Entity("His.Hope.AgentHarness.Core.Models.Artifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("Content")
                        .HasColumnType("bytea")
                        .HasColumnName("content");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid>("PipelineRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("pipeline_run_id");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("storage_ref");

                    b.HasKey("Id");

                    b.HasIndex("PipelineRunId")
                        .HasDatabaseName("ix_artifacts_pipeline_run_id");

                    b.ToTable("artifacts", "harness");
                });

            modelBuilder.Entity("His.Hope.AgentHarness.Core.Models.EvalRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("EvalSuiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("eval_suite_id");

                    b.Property<int?>("JudgeScore")
                        .HasColumnType("integer")
                        .HasColumnName("judge_score");

                    b.Property<double?>("PassAt1")
                        .HasColumnType("double precision")
                        .HasColumnName("pass_at_1");

                    b.Property<double?>("PassAtK")
                        .HasColumnType("double precision")
                        .HasColumnName("pass_at_k");

                    b.Property<string>("RawResultJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_result_json");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TargetAgent")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("target_agent");

                    b.Property<string>("TargetModel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("target_model");

                    b.HasKey("Id");

                    b.HasIndex("EvalSuiteId")
                        .HasDatabaseName("ix_eval_runs_suite_id");

                    b.HasIndex("TargetAgent")
                        .HasDatabaseName("ix_eval_runs_target_agent");

                    b.ToTable("eval_runs", "harness");
                });

            modelBuilder.Entity("His.Hope.AgentHarness.Core.Models.EvalSuite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("definition_json");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("domain");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_eval_suites_name");

                    b.ToTable("eval_suites", "harness");
                });

            modelBuilder.Entity("His.Hope.AgentHarness.Core.Models.MemoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("agent_name");

                    b.Property<decimal>("ConfidenceScore")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)")
                        .HasDefaultValue(0.85m)
                        .HasColumnName("confidence_score");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(256)")
                        .HasColumnName("embedding");

                    b.Property<string>("ErrorCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("error_category");

                    b.Property<string>("ErrorPattern")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("error_pattern");

                    b.Property<string>("FixArtifactRef")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("fix_artifact_ref");

                    b.Property<string>("FixDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fix_description");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("keywords");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<int>("UseCount")
                        .HasColumnType("integer")
                        .HasColumnName("use_count");

                    b.HasKey("Id");

                    b.HasIndex("AgentName")
                        .HasDatabaseName("ix_memory_agent_name");

                    b.HasIndex("ErrorCategory")
                        .HasDatabaseName("ix_memory_error_category");

                    b.ToTable("memory_entries", "harness");
                });

            modelBuilder.Entity("His.Hope.AgentHarness.Core.Models.PendingApproval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action_type");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("approved_by");

                    b.Property<string>("ContextJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("context");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<string>("RejectReason")
                        .HasColumnType("text")
                        .HasColumnName("reject_reason");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("requested_by");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_pending_approvals_status");

                    b.ToTable("pending_approvals", "harness");
                });

            modelBuilder.Entity("His.Hope.AgentHarness.Core.Models.PipelineCheckpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompletedNodeIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("completed_node_ids");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailedNodeIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("failed_node_ids");

                    b.Property<int>("LoopIteration")
                        .HasColumnType("integer")
                        .HasColumnName("loop_iteration");

                    b.Property<string>("NodeStatesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("node_states");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phase");

                    b.Property<Guid>("PipelineRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("pipeline_run_id");

                    b.HasKey("Id");

                    b.HasIndex("PipelineRunId")
                        .HasDatabaseName("ix_checkpoints_pipeline_run_id");

                    b.HasIndex("PipelineRunId", "CreatedAt")
                        .HasDatabaseName("ix_checkpoints_pipeline_run_created");

                    b.ToTable("pipeline_checkpoints", "harness");
                });

            modelBuilder.Entity("His.Hope.AgentHarness.Core.Models.PipelineRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters");

                    b.Property<Guid?>("ParentPipelineRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_pipeline_run_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("TimeoutAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timeout_at");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("triggered_by");

                    b.Property<string>("WorkflowId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id");

                    b.HasIndex("ParentPipelineRunId")
                        .HasDatabaseName("ix_pipeline_runs_parent_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_pipeline_runs_status");

                    b.ToTable("pipeline_runs", "harness");
                });

            modelBuilder.Entity("His.Hope.AgentHarness.Core.Models.QualityGate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evaluated_at");

                    b.Property<string>("GateId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("gate_id");

                    b.Property<string>("GateName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("gate_display_name");

                    b.Property<string>("GateType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("gate_name");

                    b.Property<string>("Output")
                        .HasColumnType("text")
                        .HasColumnName("output");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean")
                        .HasColumnName("passed");

                    b.Property<Guid>("PipelineRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("pipeline_run_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("severity");

                    b.HasKey("Id");

                    b.HasIndex("PipelineRunId")
                        .HasDatabaseName("ix_quality_gate_results_pipeline_run_id");

                    b.ToTable("quality_gate_results", "harness");
                });

            modelBuilder.Entity("His.Hope.AgentHarness.Core.Models.EvalRun", b =>
                {
                    b.HasOne("His.Hope.AgentHarness.Core.Models.EvalSuite", null)
                        .WithMany()
                        .HasForeignKey("EvalSuiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_eval_runs_suite_id");
                });
#pragma warning restore 612, 618
        }
    }
}
