import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HisHopeDataTableComponent, HisHopeDataTableColumn, HisHopeI18nService, HisHopePageHeaderComponent, HisHopePageLayoutComponent, HisHopeToolbarComponent, HisHopeTranslatePipe } from '@his-hope/frontend-foundation';
import { AdminApiService } from '../../core/services/admin-api.service';

@Component({selector:'app-iam-api-audiences-page',standalone:true,imports:[CommonModule,HisHopeDataTableComponent,HisHopePageHeaderComponent,HisHopePageLayoutComponent,HisHopeToolbarComponent,HisHopeTranslatePipe],template:`<hh-page-layout><hh-page-header hhPageHeader [title]="'admin.apiAudiences'|hhTranslate:'API audiences'" [subtitle]="'admin.apiAudiencesSubtitle'|hhTranslate:'Resource audiences exposed by Identity Service.'"/><hh-toolbar hhPageToolbar><button hhToolbarActions type="button" class="hh-button hh-button--secondary" (click)="load()">{{'admin.refresh'|hhTranslate}}</button></hh-toolbar><div *ngIf="error" class="hh-state hh-state--error">{{error}}</div><hh-data-table [columns]="columns" [rows]="rows" [loading]="loading" [empty]="!loading&&!rows.length"></hh-data-table></hh-page-layout>`})
export class IamApiAudiencesPageComponent implements OnInit {private readonly api=inject(AdminApiService);private readonly i18n=inject(HisHopeI18nService);rows:Record<string,unknown>[]=[];loading=false;error='';get columns():HisHopeDataTableColumn[]{return[{key:'key',label:this.i18n.t('admin.key','Key')},{key:'displayName',label:this.i18n.t('admin.displayName','Display name')},{key:'audience',label:this.i18n.t('admin.audience','Audience')},{key:'scopeId',label:this.i18n.t('admin.scopeId','Scope')},{key:'lifecycleStatus',label:this.i18n.t('admin.status','Status')}];}ngOnInit(){this.load();}load(){this.loading=true;this.api.getIamApiAudiences().subscribe({next:x=>this.rows=x.audiences.map(item=>({...item})),error:()=>{this.error=this.i18n.t('admin.iamLoadFailed','Unable to load API audiences.');this.loading=false;},complete:()=>this.loading=false});}}

@Component({selector:'app-iam-trusted-issuers-page',standalone:true,imports:[CommonModule,HisHopeDataTableComponent,HisHopePageHeaderComponent,HisHopePageLayoutComponent,HisHopeToolbarComponent,HisHopeTranslatePipe],template:`<hh-page-layout><hh-page-header hhPageHeader [title]="'admin.trustedIssuers'|hhTranslate:'Trusted issuers'" [subtitle]="'admin.trustedIssuersSubtitle'|hhTranslate:'Configured OIDC/SAML issuer metadata.'"/><hh-toolbar hhPageToolbar><button hhToolbarActions type="button" class="hh-button hh-button--secondary" (click)="load()">{{'admin.refresh'|hhTranslate}}</button></hh-toolbar><div *ngIf="error" class="hh-state hh-state--error">{{error}}</div><hh-data-table [columns]="columns" [rows]="rows" [loading]="loading" [empty]="!loading&&!rows.length"></hh-data-table></hh-page-layout>`})
export class IamTrustedIssuersPageComponent implements OnInit {private readonly api=inject(AdminApiService);private readonly i18n=inject(HisHopeI18nService);rows:Record<string,unknown>[]=[];loading=false;error='';get columns():HisHopeDataTableColumn[]{return[{key:'key',label:this.i18n.t('admin.key','Key')},{key:'displayName',label:this.i18n.t('admin.displayName','Display name')},{key:'issuer',label:this.i18n.t('admin.issuer','Issuer')},{key:'protocol',label:this.i18n.t('admin.protocol','Protocol')},{key:'active',label:this.i18n.t('admin.active','Active')}];}ngOnInit(){this.load();}load(){this.loading=true;this.api.getIamTrustedIssuers().subscribe({next:x=>this.rows=x.issuers.map(item=>({...item})),error:()=>{this.error=this.i18n.t('admin.iamLoadFailed','Unable to load trusted issuers.');this.loading=false;},complete:()=>this.loading=false});}}

@Component({selector:'app-iam-external-identities-page',standalone:true,imports:[CommonModule,HisHopeDataTableComponent,HisHopePageHeaderComponent,HisHopePageLayoutComponent,HisHopeToolbarComponent,HisHopeTranslatePipe],template:`<hh-page-layout><hh-page-header hhPageHeader [title]="'admin.externalIdentities'|hhTranslate:'External identities'" [subtitle]="'admin.externalIdentitiesSubtitle'|hhTranslate:'Configured browser federation providers. Secrets stay server-side.'"/><hh-toolbar hhPageToolbar><button hhToolbarActions type="button" class="hh-button hh-button--secondary" (click)="load()">{{'admin.refresh'|hhTranslate}}</button></hh-toolbar><div *ngIf="error" class="hh-state hh-state--error">{{error}}</div><hh-data-table [columns]="columns" [rows]="rows" [loading]="loading" [empty]="!loading&&!rows.length"></hh-data-table></hh-page-layout>`})
export class IamExternalIdentitiesPageComponent implements OnInit {private readonly api=inject(AdminApiService);private readonly i18n=inject(HisHopeI18nService);rows:Record<string,unknown>[]=[];loading=false;error='';get columns():HisHopeDataTableColumn[]{return[{key:'provider',label:this.i18n.t('admin.provider','Provider')},{key:'displayName',label:this.i18n.t('admin.displayName','Display name')},{key:'protocol',label:this.i18n.t('admin.protocol','Protocol')},{key:'loginUrl',label:this.i18n.t('admin.loginUrl','Login URL')}];}ngOnInit(){this.load();}load(){this.loading=true;this.api.getExternalIdentityProviders().subscribe({next:x=>this.rows=x.providers.map(item=>({...item})),error:()=>{this.error=this.i18n.t('admin.iamLoadFailed','Unable to load external identities.');this.loading=false;},complete:()=>this.loading=false});}}
