agent {
    data_dir = "/run/spire/data"
    log_level = "INFO"
    server_address = "spire-server-1"
    server_port = "8081"
    socket_path = "/run/spire/sockets/agent.sock"
    trust_domain = "his-hope.local"
    trust_bundle_path = "/run/secrets/spire_server_bundle.pem"
}

plugins {
    NodeAttestor "x509pop" {
        plugin_data {
            cert_file = "/run/secrets/spire_agent_cert.pem"
            key_file = "/run/secrets/spire_agent_key.pem"
        }
    }
    KeyManager "disk" {
        plugin_data {
            directory = "/run/spire/data"
        }
    }
    WorkloadAttestor "unix" {
        plugin_data {}
    }
}
