log_level = "info"
domains = ["spire-oidc"]
insecure_addr = "0.0.0.0:8082"
allow_insecure_scheme = true
jwt_issuer = "http://spire-oidc:8082"
jwks_uri = "http://spire-oidc:8082/keys"

workload_api {
    socket_path = "/run/spire/sockets/agent.sock"
    trust_domain = "his-hope.local"
    poll_interval = "10s"
}
