server {
    bind_address = "0.0.0.0"
    bind_port = "8081"
    socket_path = "/run/spire/sockets/server.sock"
    trust_domain = "his-hope.local"
    data_dir = "/run/spire/data"
    log_level = "INFO"
    default_x509_svid_ttl = "1h"
    default_jwt_svid_ttl = "15m"
    jwt_key_type = "ec-p256"
}

plugins {
    DataStore "sql" {
        plugin_data {
            database_type = "sqlite3"
            connection_string = "/run/spire/data/datastore.sqlite3"
        }
    }
    NodeAttestor "join_token" {
        plugin_data {}
    }
    KeyManager "disk" {
        plugin_data {
            keys_path = "/run/spire/data/keys.json"
        }
    }
}
