apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
spec:
  template:
    spec:
      containers:
        - name: appointment-service
          livenessProbe:
            httpGet:
              path: /health/live
