apiVersion: v1
kind: Secret
metadata:
  name: clinical-bff-secrets
type: Opaque
stringData:
  redis-connection: redis:6379,abortConnect=false
---
apiVersion: v1
kind: Secret
metadata:
  name: billing-bff-secrets
type: Opaque
stringData:
  redis-connection: redis:6379,abortConnect=false
---
apiVersion: v1
kind: Secret
metadata:
  name: dashboard-bff-secrets
type: Opaque
stringData:
  redis-connection: redis:6379,abortConnect=false
---
apiVersion: v1
kind: Secret
metadata:
  name: lab-bff-secrets
type: Opaque
stringData:
  redis-connection: redis:6379,abortConnect=false
---
apiVersion: v1
kind: Secret
metadata:
  name: patient-bff-secrets
type: Opaque
stringData:
  redis-connection: redis:6379,abortConnect=false
---
apiVersion: v1
kind: Secret
metadata:
  name: pharmacy-bff-secrets
type: Opaque
stringData:
  redis-connection: redis:6379,abortConnect=false
