apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-identity-service-vault-egress
spec:
  podSelector:
    matchLabels:
      app: identity-service
  policyTypes:
    - Egress
  egress:
    - ports:
        - port: 8200
          protocol: TCP
      to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: vault
              app.kubernetes.io/part-of: his-hope
              environment: dev
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
      to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
