apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/part-of: his-hope
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: his-hope-vault-auth-delegator
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/part-of: his-hope
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: his-hope-dev
