apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  namespace: his-hope
  name: patient-service-grpc
  labels:
    app.kubernetes.io/part-of: his-hope
    app.kubernetes.io/name: patient-service
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: patient-service
  port: grpc
  proxyProtocol: gRPC
---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  namespace: his-hope
  name: patient-service-http
  labels:
    app.kubernetes.io/part-of: his-hope
    app.kubernetes.io/name: patient-service
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: patient-service
  port: http
  proxyProtocol: HTTP/1
---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  namespace: his-hope
  name: identity-service-grpc
  labels:
    app.kubernetes.io/part-of: his-hope
    app.kubernetes.io/name: identity-service
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: identity-service
  port: grpc
  proxyProtocol: gRPC
---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  namespace: his-hope
  name: identity-service-http
  labels:
    app.kubernetes.io/part-of: his-hope
    app.kubernetes.io/name: identity-service
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: identity-service
  port: http
  proxyProtocol: HTTP/1
---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  namespace: his-hope
  name: appointment-service-grpc
  labels:
    app.kubernetes.io/part-of: his-hope
    app.kubernetes.io/name: appointment-service
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: appointment-service
  port: grpc
  proxyProtocol: gRPC
---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  namespace: his-hope
  name: appointment-service-http
  labels:
    app.kubernetes.io/part-of: his-hope
    app.kubernetes.io/name: appointment-service
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: appointment-service
  port: http
  proxyProtocol: HTTP/1
---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  namespace: his-hope
  name: lab-bff-http
  labels:
    app.kubernetes.io/part-of: his-hope
    app.kubernetes.io/name: lab-bff
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: lab-bff
  port: http
  proxyProtocol: HTTP/1
---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  namespace: his-hope
  name: clinical-bff-http
  labels:
    app.kubernetes.io/part-of: his-hope
    app.kubernetes.io/name: clinical-bff
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: clinical-bff
  port: http
  proxyProtocol: HTTP/1
---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  namespace: his-hope
  name: clinical-service-grpc
  labels:
    app.kubernetes.io/part-of: his-hope
    app.kubernetes.io/name: clinical-service
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: clinical-service
  port: grpc
  proxyProtocol: gRPC
---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  namespace: his-hope
  name: clinical-service-http
  labels:
    app.kubernetes.io/part-of: his-hope
    app.kubernetes.io/name: clinical-service
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: clinical-service
  port: http
  proxyProtocol: HTTP/1
---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  namespace: his-hope
  name: billing-bff-http
  labels:
    app.kubernetes.io/part-of: his-hope
    app.kubernetes.io/name: billing-bff
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: billing-bff
  port: http
  proxyProtocol: HTTP/1
