apiVersion: apps/v1
kind: Deployment
metadata:
  name: ignored-by-target
spec:
  template:
    metadata:
      annotations:
        # Linkerd injects the configured version after the image name. Keep
        # the digest in the version field so the resulting OCI references are
        # name:tag@sha256:digest (rather than name@sha256:digest:tag).
        config.linkerd.io/proxy-image: cr.l5d.io/linkerd/proxy
        config.linkerd.io/proxy-version: stable-2.14.10@sha256:7876cee0717575ebc39d2b7cfd701e0df28a809bcb2cf4974716a0bce1ce32cb
        config.linkerd.io/init-image: cr.l5d.io/linkerd/proxy-init
        config.linkerd.io/init-image-version: v2.2.3@sha256:1075bc22a4f8a0852311dc84c9db0552f1245d07fe4fdebd4bc6cf4566bcbc76
