apiVersion: apps/v1
kind: Deployment
metadata:
  name: ignored-by-target
spec:
  template:
    metadata:
      annotations:
        config.linkerd.io/proxy-image: cr.l5d.io/linkerd/proxy@sha256:7876cee0717575ebc39d2b7cfd701e0df28a809bcb2cf4974716a0bce1ce32cb
        config.linkerd.io/proxy-init-image: cr.l5d.io/linkerd/proxy-init@sha256:1075bc22a4a8f0852311dc84c9db0552f1245d07fe4fdebd4bc6cf4566bcbc76
